"use client";
import {getVault} from '@/lib/browser-vault';
import {useEffect,useState} from 'react';
import {Fingerprint,ShieldCheck,KeyRound,Check,Smartphone} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type Preferences={passkey:boolean;mfa:boolean};
const EMPTY:Preferences={passkey:false,mfa:false};
export function AccountSecurity({compact=false,onContinue,storageKey='training-studio-security-preview-v1'}:{compact?:boolean;onContinue?:()=>void;storageKey?:string}){
 const [preferences,setPreferences]=useState<Preferences>(EMPTY),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[flow,setFlow]=useState(''),[stage,setStage]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[unavailable,setUnavailable]=useState(false),[expired,setExpired]=useState(false),[attempts,setAttempts]=useState(0);
 useEffect(()=>{let alive=true;(async()=>{try{const raw=await getVault()?.read(storageKey);const p=JSON.parse(raw||'null');if(p&&alive)setPreferences({passkey:p.passkey===true,mfa:p.mfa===true})}catch{}if(alive)setLoaded(true)})();return()=>{alive=false}},[storageKey]);
 const save=(p:Preferences)=>{setPreferences(p);void getVault()?.write(storageKey,JSON.stringify(p)).catch(()=>{})};
 const start=(kind:string)=>{setFlow(kind);setStage(kind==='google'?'provider':kind==='passkey'?'device':kind==='enroll-passkey'?'register':kind==='enroll-mfa'?'enroll':kind==='remove-mfa'?'remove':'recovery');setError('');setCode('');setAttempts(0);setUnavailable(false);setExpired(false);setOpen(true)};
 const signedIn=()=>{if(preferences.mfa){setStage('challenge');setCode('')}else setStage('success')};
 const verify=()=>{if(expired){setError('This sample code has expired. Generate a new sample challenge.');return}if(attempts>=3){setError('Sample retry limit reached. Generate a new challenge to continue.');return}if(code!=='123456'){setAttempts(v=>v+1);setError('Incorrect sample code. Use 123456 for this preview.');return}if(flow==='enroll-mfa')save({...preferences,mfa:true});if(flow==='remove-mfa')save({...preferences,mfa:false});setStage('success');setError('')};
 const login=flow==='google'||flow==='passkey';
 return <section className={compact?'security-preview compact':'card security-preview'}>{!compact&&<><p className="eyebrow">ACCOUNT SECURITY · PREVIEW</p><h2>Choose how you’ll sign in.</h2><p className="muted">Explore the intended Google, passkey and optional authenticator flows. These controls do not activate real security.</p></>}<div className="security-actions">{compact?<><Button variant="outline" onClick={()=>start('google')}><span className="google-letter" aria-hidden="true">G</span>Preview Google sign-in</Button><Button variant="outline" onClick={()=>start('passkey')}><Fingerprint/>Preview passkey sign-in</Button></>:<><div className="security-method"><span className="method-icon google-letter">G</span><div><h3>Google account</h3><p>Sign in with a verified Google identity.</p><span className="pill">Not connected</span></div><Button variant="outline" onClick={()=>start('google')}>Preview sign-in</Button></div><div className="security-method"><Fingerprint className="method-icon"/><div><h3>Passkey</h3><p>Face ID, fingerprint, or device PIN. This preview does not use your device’s biometrics yet, and no sign-in service is connected.</p><span className="pill">{preferences.passkey?'Enrolled in preview only':'Not connected'}</span></div><Button variant="outline" onClick={()=>start(preferences.passkey?'passkey':'enroll-passkey')}>{preferences.passkey?'Try preview':'Preview setup'}</Button></div><div className="security-method"><Smartphone className="method-icon"/><div><h3>Optional two-factor verification</h3><p>An authenticator-app code and a recovery method. A user-verified passkey can already provide multiple authentication factors.</p><span className="pill">{preferences.mfa?'Enabled in preview only':'Optional · not enabled'}</span></div><Button variant="outline" disabled={!loaded} onClick={()=>start(preferences.mfa?'remove-mfa':'enroll-mfa')}>{preferences.mfa?'Preview disabling':'Preview setup'}</Button></div><Button variant="ghost" onClick={()=>start('recovery')}>Explore lost-device recovery</Button></>}</div>{compact&&<details><summary>Try optional account protection</summary><div className="button-row"><Button size="sm" variant="outline" onClick={()=>start('enroll-passkey')}>Set up passkey preview</Button><Button size="sm" variant="outline" onClick={()=>start(preferences.mfa?'remove-mfa':'enroll-mfa')}>{preferences.mfa?'Disable 2FA preview':'Set up 2FA preview'}</Button></div></details>}{!compact&&<div className="notice blue"><ShieldCheck/><p>This Site’s existing private ChatGPT access is real. The app’s Google login, passkeys, authenticator codes and cross-device accounts still need a connected authentication service. No passwords, biometric data or authenticator secrets are collected here.</p></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="security-dialog"><DialogHeader><DialogTitle>{stage==='success'?'Preview completed':flow==='google'?'Google sign-in preview':flow.includes('passkey')?'Passkey preview':flow==='recovery'?'Recovery preview':'Two-factor verification preview'}</DialogTitle><DialogDescription>Simulation only. Use the displayed sample information.</DialogDescription></DialogHeader>
 {stage==='provider'&&<><div className="local-account"><span className="google-letter">G</span><div><b>Example Google account</b><p>athlete@example.test</p></div></div><p className="small-copy">In the real app, Google handles sign-in on its own secure screen. This sample does not contact Google or switch to another person’s records.</p><Button onClick={signedIn}>Use example account</Button></>}
 {(stage==='device'||stage==='register')&&<><Fingerprint className="security-hero-icon"/><h3>{stage==='register'?'Create a passkey on your device':'Confirm with your device'}</h3><p className="muted">The real flow uses your device’s Face ID, fingerprint, security key, or PIN. The app would receive proof of verification, never your biometric data.</p>{unavailable?<div className="notice warning"><div><p>No suitable passkey is available in this scenario.</p><Button variant="outline" onClick={()=>{setFlow('google');setStage('provider');setUnavailable(false)}}>Use Google preview instead</Button><Button variant="ghost" onClick={()=>{setFlow('recovery');setStage('recovery');setUnavailable(false)}}>Explore recovery</Button></div></div>:<Button onClick={()=>{if(stage==='register'){save({...preferences,passkey:true});setStage('success')}else signedIn()}}>Simulate successful device confirmation</Button>}<Button variant="ghost" onClick={()=>setUnavailable(true)}>Try an unavailable-device scenario</Button></>}
 {stage==='enroll'&&<><Smartphone className="security-hero-icon"/><h3>Add an authenticator app</h3><p className="muted">The real service would show a one-time setup QR code, verify your first code, and set up recovery by verified email or a second factor. This preview uses no real QR code or secret.</p><Button onClick={()=>setStage('challenge')}>Try the sample verification</Button></>}
 {stage==='remove'&&<><p className="muted">The real app would require recent verification before removing an extra factor. This only changes a preview preference.</p><Button variant="outline" onClick={()=>setStage('challenge')}>Verify before disabling preview</Button></>}
 {stage==='challenge'&&<><label className="field"><span>Sample six-digit code</span><Input inputMode="numeric" autoComplete="off" maxLength={6} value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,''));setError('')}} placeholder="123456"/><small>Use 123456. Never enter a real authentication code here.</small></label>{error&&<p role="alert" className="error-text">{error}</p>}<Button disabled={code.length!==6||attempts>=3||expired} onClick={verify}>Verify sample code</Button><div className="button-row"><Button variant="ghost" onClick={()=>{setExpired(true);setError('Sample challenge expired. Start a new challenge below.')}}>Try expired code</Button><Button variant="ghost" onClick={()=>{setExpired(false);setAttempts(0);setCode('');setError('')}}>New sample challenge</Button><Button variant="ghost" onClick={()=>setStage('recovery')}>Lost your device?</Button></div></>}
 {stage==='recovery'&&<><KeyRound className="security-hero-icon"/><h3>Keep a way back into your account</h3><p className="muted">The planned account flow has no username or password. Access is recovered through a verified email address or another second factor. Losing a device must not bypass optional verification.</p><div className="notice"><p><b>Example recovery route</b><br/>A one-time code sent to athlete@example.test, or a second factor you set up earlier.<br/>This is an illustration, not a usable credential.</p></div><Button onClick={()=>setStage('recovered')}>Simulate verified recovery</Button></>}
 {stage==='recovered'&&<><Check className="security-hero-icon"/><h3>Recovery journey previewed</h3><p className="muted">A real account would verify the email address or second factor before restoring access. No account was recovered or changed here.</p><Button onClick={()=>setOpen(false)}>Return to account options</Button></>}
 {stage==='success'&&<><ShieldCheck className="security-hero-icon"/><h3>{login?'Demo sign-in completed':flow==='enroll-mfa'?'Two-factor preview enabled':flow==='remove-mfa'?'Two-factor preview disabled':'Passkey preview enrolled'}</h3><p className="muted">{login?'You can now continue with the saved training on this browser. No external account was authenticated.':'Only the demo preference was saved. Real authentication has not been configured.'}</p>{flow==='enroll-mfa'&&<Button variant="outline" onClick={()=>setStage('recovery')}>Preview recovery instructions</Button>}<Button onClick={()=>{setOpen(false);if(login)onContinue?.()}}>{login&&onContinue?'Continue demo journey':'Done'}</Button></>}
 {stage!=='success'&&stage!=='recovered'&&<Button variant="ghost" onClick={()=>setOpen(false)}>Cancel preview</Button>}</DialogContent></Dialog>
 </section>
}
