"use client";
// Static guide photos with a separate rights gate; the unused dynamic image endpoint is closed.
/* eslint-disable @next/next/no-img-element */
import {type Exercise,loadConvention} from '@/lib/training';
import {ExternalLink,BookOpen} from 'lucide-react';
import {useState} from 'react';
import {exercisePhotoRightsCleared,type MovementGuide,type ExerciseMedia} from '@/lib/exercise-content';
export type {MovementGuide} from '@/lib/exercise-content';
function GuidePhoto({src,name,index}:{src:string;name:string;index:number}){const [failed,setFailed]=useState(false);return <figure>{failed?<p role="status">Photo unavailable. Use the movement steps below.</p>:<img src={src} alt={`${name} · source photo ${index+1}`} loading="lazy" width={360} height={360} onError={()=>setFailed(true)}/>}<figcaption>View {index+1}</figcaption></figure>}
function safeLink(url:unknown){try{const u=new URL(String(url));return u.protocol==='https:'&&!u.username&&!u.password?u.href:null}catch{return null}}
const TERMS=[{term:'Rep',meaning:'One full movement, from the start and back again.'},{term:'Set',meaning:'A group of reps done before a rest.'},{term:'Load',meaning:'The weight or resistance used for an exercise.'},{term:'RIR · reps in reserve',meaning:'How many more reps you think you could do with the same form.'},{term:'1RM',meaning:'The most weight you can lift for one full rep. An estimated 1RM is a guess from a lighter set.'}];
export function ExerciseGuide({exercise:e,guide:g,media,custom=[],loading=false}:{exercise:Exercise;guide?:MovementGuide;media?:ExerciseMedia;custom?:Exercise[];loading?:boolean}){
 const demo=safeLink(media?.videoUrl||media?.sourceUrl),cues=g?.quickCues||e.cues.slice(0,3),sourceURLs=(g?.sourceURLs||[e.source]).map(safeLink).filter((x):x is string=>!!x);
 const photos=(exercisePhotoRightsCleared&&Array.isArray(media?.images)?media.images:[]).filter((x:unknown):x is string=>typeof x==='string'&&/^\/exercise-photos\/[a-zA-Z0-9_/-]+\.jpg$/.test(x));
 return <div className="movement-guide" aria-busy={loading}><p className="guide-status" role="status">{loading?'Loading movement guide…':g?'Step-by-step guide · sources linked below':e.custom?'Your exercise · no guide saved':'Guide unavailable'}</p><p className="guide-summary">{g?.summary||(e.custom?'No guide is saved for this custom exercise. Use instructions you trust.':loading?'Your saved workout stays open while the guide loads.':'The guide could not load. Check your connection and open this exercise again.')}</p>
 {cues.length>0&&<section className="guide-at-glance"><h3>At a glance</h3><ul>{cues.map((c,i)=><li key={i}>{c}</li>)}</ul></section>}
 {demo?<a className="guide-demo-link" href={demo} target="_blank" rel="noopener noreferrer"><BookOpen size={18}/>{media?.hasVideo?'Watch a demo on the source site':'See the source instructions'}<ExternalLink size={16}/></a>:<p className="guide-media-note">No video is linked for this variation yet.</p>}
 {photos.length>0&&<section className="guide-photos"><h3>Source photos</h3><div>{photos.map((src:string,i:number)=><GuidePhoto key={src} src={src} name={e.name} index={i}/>)}</div><p>Photos from the linked exercise source. Follow the written steps for the full movement.</p></section>}
 {g?<><p className="variant-label">{g.variant}</p>{g.equipment?.length&&<section className="instruction-section"><h3>What you need</h3><ul className="equipment-list">{g.equipment.map((x,i)=><li key={i}>{x}</li>)}</ul></section>}{([{title:'Set up',steps:g.setup},{title:'Do the movement',steps:g.execution},{title:'Finish the set',steps:g.finish||[]}] as const).map(({title,steps})=>steps.length>0&&<section className="instruction-section" key={title}><h3>{title}</h3><ol className="cue-list">{steps.map((c,i)=><li key={i}>{c}</li>)}</ol></section>)}<section className="instruction-section"><h3>Breathing</h3>{g.breathing.map((x,i)=><p key={i}>{x}</p>)}</section></>:!e.custom&&<section className="instruction-section"><h3>Movement steps</h3><ol className="cue-list">{e.cues.map((c,i)=><li key={i}>{c}</li>)}</ol></section>}
 <section className="record-guide"><h3>What to record</h3><p>{g?.loadConvention||loadConvention(e.id,custom)}</p><p>A blank load means it was not recorded. It does not mean zero.</p></section>
 {g&&<><details className="guide-extra"><summary>Common mistakes</summary><ul>{g.commonErrors.map((x,i)=><li key={i}>{x}</li>)}</ul></details><details className="guide-extra"><summary>Make the movement easier</summary><p>{g.easierOption}</p></details><div className="guide-safety"><h3>Before you start</h3><p>{g.safety}</p><p>This guide describes the movement. The app cannot see or check your form.</p></div></>}
 <details className="guide-extra"><summary>Workout terms</summary><dl>{[...(g?.terms||[]),...TERMS].filter((x,i,a)=>a.findIndex(y=>y.term===x.term)===i).map(x=><div key={x.term}><dt>{x.term}</dt><dd>{x.meaning}</dd></div>)}</dl></details>
 <details className="guide-extra"><summary>Sources</summary><p>{g?.sourceNote||'No source note is saved for this custom movement.'}</p>{sourceURLs.map((url,i)=><a href={url} key={i} className="instruction-source" target="_blank" rel="noopener noreferrer">Source {i+1}<ExternalLink size={14}/></a>)}<p>Source links open another site.</p></details>
 </div>;
}
