"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {maxBackupBytes,previewBackup,serializeBackup,type restoreBackup} from '@/lib/local-backup';
import type {State} from '@/lib/training';
type Preview=ReturnType<typeof previewBackup> & {expected:string};
export function LocalBackup({state,disabled,onRestore}:{state:State;disabled:boolean;onRestore:(incoming:Parameters<typeof restoreBackup>[1],expected:string)=>boolean}){
 const [preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const exportRecords=()=>{try{const raw=serializeBackup(state),url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='movefield-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setError('')}catch{setError('The backup could not be prepared. Your records have not been changed.')}};
 return <section className="card"><h2>Backup and restore</h2><p>Save a copy before clearing browser data or changing devices. A compatible website or phone backup can replace the records on this device.</p><p className="small-copy">Backups include your profile and workout notes. Keep them somewhere private. This is a manual transfer, with no account or automatic sync.</p><div className="button-row"><Button variant="outline" disabled={disabled||busy} onClick={exportRecords}>Export backup</Button></div><label className="field"><span>Choose a backup to review</span><input type="file" accept="application/json,.json" disabled={disabled||busy||!!state.active} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setBusy(true);try{const expected=serializeBackup(state);if(file.size>maxBackupBytes)throw Error('This backup is too large to open here.');setPreview({...previewBackup(await file.text()),expected})}catch(err){setError(err instanceof Error?err.message:'The backup could not be opened.')}finally{setBusy(false)}}}/></label>{state.active&&<p className="small-copy">Finish or discard your active workout before restoring another backup.</p>}{busy&&<p role="status">Opening backup…</p>}{error&&<p role="alert" className="error-text">{error}</p>}<AlertDialog open={!!preview} onOpenChange={open=>{if(!open)setPreview(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace this device’s records?</AlertDialogTitle><AlertDialogDescription>{preview&&<>Backup profile: {preview.name||'Unnamed'}. {preview.workouts} workouts, {preview.sets} logged sets and {preview.plans} plans. {preview.active?'An unfinished workout will be available to resume. ':''}This replaces your current {state.history.length} workouts and plan. Export your current records first. Other devices are unaffected.</>}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep current records</AlertDialogCancel><AlertDialogAction onClick={()=>{if(preview&&onRestore(preview.state,preview.expected))setPreview(null);else setError('The restore could not be saved. Choose the backup again to review current records.')}}>Replace with this backup</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
