"use client";
import {useState,useMemo} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {type State,type Exercise,exercises,uid,requiresSetup,niceDate,matchesExercise} from '@/lib/training';
import {type Addition,previewAddition,applyAddition} from '@/lib/customize';
const conventions=[{id:'total',name:'Total load · repetitions total',multiplier:1},{id:'pair',name:'Per hand · both arms together',multiplier:2},{id:'onearm',name:'One hand · repetitions per side, both sides',multiplier:2},{id:'one',name:'One implement · repetitions total',multiplier:1},{id:'pairlegs',name:'Two dumbbells · reps per leg, both legs',multiplier:4},{id:'none',name:'Bodyweight / timed / unquantified resistance',multiplier:0}];
const equipment=['Barbell','Dumbbell','Kettlebell','Cable','Plate-loaded machine','Selectorized machine','Bodyweight','Resistance band','Other / unspecified'];
export function PlanCustomizer({state:s,sessionId,onClose,onApply}:{state:State;sessionId:string;onClose:()=>void;onApply:(s:State)=>void}){
 const [version]=useState(s.plan?.version||0),[planId]=useState(s.plan?.id||''),[q,setQ]=useState(''),[eq,setEq]=useState('All'),[selected,setSelected]=useState<Exercise|null>(null),[sets,setSets]=useState(2),[lo,setLo]=useState(8),[hi,setHi]=useState(12),[rest,setRest]=useState(90),[all,setAll]=useState(true),[allowLonger,setAllowLonger]=useState(false),[setup,setSetup]=useState(''),[convention,setConvention]=useState(''),[exactEquipment,setExactEquipment]=useState('Dumbbell'),[metric,setMetric]=useState<'reps'|'seconds'|'minutes'>('reps'),[progress,setProgress]=useState(false),[review,setReview]=useState(false),[error,setError]=useState(''),[newId]=useState(()=>uid('variant'));
 const needsConfig=selected?.instructionStatus==='imported-reference'||(selected?.custom&&!selected.loadConvention);
 const chosen=useMemo(()=>{if(!selected)return null;if(!needsConfig)return selected;const c=conventions.find(x=>x.id===convention);return{...selected,id:newId,name:selected.name+' · my '+exactEquipment.toLowerCase()+' variation',equipment:exactEquipment,metric,custom:true,instructionStatus:selected.instructionStatus,loadTracked:!!c?.multiplier,loadMultiplier:c?.multiplier||0,requiresSetup:['Cable','Plate-loaded machine','Selectorized machine'].includes(exactEquipment),loadConvention:(c?.name||'Not configured')+'. '+(['Cable','Plate-loaded machine','Selectorized machine'].includes(exactEquipment)?'Record displayed stack or total added plates, and the exact machine/settings. Loads are not comparable across machines.':'For bars include the bar. Keep the same range and technique.'),progressionEnabled:progress&&!!c?.multiplier&&metric==='reps'} as Exercise},[selected,needsConfig,convention,newId,exactEquipment,metric,progress]);
 const base=s.plan?.sessions.find(x=>x.id===sessionId);
 const a:Addition|null=chosen?{sessionId,exercise:chosen,sets,lo,hi:metric==='reps'?hi:lo,rest,all,setup,allowLonger,planId,version}:null;
 const preview=a?previewAddition(s,a):null;
 const list=[...exercises,...s.custom].filter(e=>(eq==='All'||e.equipment===eq)&&matchesExercise(e,q));
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="customize-dialog"><DialogHeader><DialogTitle>Customize your plan</DialogTitle><DialogDescription>{base?.title} · {base&&niceDate(base.date)}. Add work, review the time, then accept.</DialogDescription></DialogHeader>
 {!selected?<><div className="field-grid"><label className="field">Find an exercise<Input autoFocus aria-label="Find an exercise to add" placeholder="e.g. cable crunch, leg press" value={q} onChange={e=>setQ(e.target.value)}/></label><label className="field">Equipment<select aria-label="Filter equipment to add" value={eq} onChange={e=>setEq(e.target.value)}><option>All</option>{[...new Set([...exercises,...s.custom].map(e=>e.equipment))].sort().map(e=><option key={e}>{e}</option>)}</select></label></div><p className="small-copy">{list.length} matches · showing the first 30. Search to narrow the library.</p><div className="customize-results">{list.slice(0,30).map(e=><button key={e.id} onClick={()=>{setSelected(e);setMetric(e.metric);setLo(e.metric==='reps'?8:30);setHi(e.metric==='reps'?12:30);setSetup(s.loadContext?.[e.id]||'')}}><b>{e.name}</b><span>{e.equipment} · {e.pattern}</span></button>)}</div>{!list.length&&<p>No matches. Create your own movement in Exercises, then add it here.</p>}</>:<>
 <div className="split"><div><h3>{selected.name}</h3><p className="small-copy">{chosen?.equipment} · {selected.custom?'Your exercise · instructions not added':'Step-by-step guide available'}</p></div><Button variant="ghost" onClick={()=>{setSelected(null);setReview(false);setConvention('');setProgress(false);setError('')}}>Choose another</Button></div>
 {needsConfig&&<div className="notice"><div><h3>Define your exact variation</h3><p>Choose how to record the weight for this variation. Its workout history will be kept separately.</p><label className="field">Equipment<select value={exactEquipment} onChange={e=>{setExactEquipment(e.target.value);setReview(false)}}>{equipment.map(e=><option key={e}>{e}</option>)}</select></label><label className="field">Metric<select value={metric} onChange={e=>{setMetric(e.target.value as Exercise['metric']);setReview(false)}}>{['reps','seconds','minutes'].map(e=><option key={e}>{e}</option>)}</select></label><label className="field">How weight is recorded<select aria-label="Weight recording convention" value={convention} onChange={e=>{setConvention(e.target.value);setReview(false)}}><option value="">Choose a convention</option>{conventions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{metric==='reps'&&convention&&convention!=='none'&&<label className="check-line"><Checkbox checked={progress} onCheckedChange={v=>{setProgress(!!v);setReview(false)}}/>Use rep-range load suggestions. I am configuring controlled resistance work, not jumps, throws, Olympic lifts or assisted/bodyweight work.</label>}</div></div>}
 <p className="metric-note"><b>Record:</b> {chosen?.loadConvention} {chosen?.progressionEnabled?'Added work uses its own comparable history, rep range and effort feedback. Load increases require approval.':'Targets and history are tracked; load increases are manual for this movement.'}</p>
 {chosen&&requiresSetup(chosen)&&<label className="field">Machine and setup label<Input maxLength={200} aria-label="Added exercise machine setup" placeholder="e.g. Gym A cable · rope · high pulley" value={setup} onChange={e=>{setSetup(e.target.value);setReview(false)}}/></label>}
 <div className="field-grid custom-targets">{[{label:'Sets',value:sets,fn:setSets},{label:metric==='reps'?'Minimum reps':metric,value:lo,fn:setLo},...(metric==='reps'?[{label:'Maximum reps',value:hi,fn:setHi}]:[]),{label:'Rest seconds',value:rest,fn:setRest}].map(f=><label className="field" key={f.label}>{f.label}<Input aria-label={f.label} type="number" min={0} value={f.value} onChange={e=>{f.fn(Number(e.target.value));setReview(false)}}/></label>)}</div>
 <label className="check-line"><Checkbox checked={all} onCheckedChange={v=>{setAll(!!v);setReview(false)}}/>Also add to future repetitions of this workout in the current block</label>
 <p className="small-copy">Other workouts keep their targets. During a lighter week, the added exercise uses half the selected sets, rounded up. Check its setup instructions before training.</p>
 {preview&&<div className="diff"><div><span>WORKOUTS UPDATED</span><b>{preview.changes.length}</b></div><div><span>LONGEST SESSION</span><b>{preview.max} min <small> / {s.plan?.profile.minutes} min window</small></b></div></div>}
 {!!preview&&preview.max>(s.plan?.profile.minutes||0)&&<label className="check-line"><Checkbox checked={allowLonger} onCheckedChange={v=>{setAllowLonger(!!v);setReview(false)}}/>I have time for the longer sessions shown. My general availability stays the same.</label>}
 {s.plan?.profile.mode==='coach'&&<p className="notice warning">This edits your tracking copy of a coach’s plan. Confirm the added work with your coach.</p>}
 {review&&preview&&<div className="customize-results review-dates">{preview.changes.map(c=><p key={c.sessionId}>{niceDate(s.plan!.sessions.find(x=>x.id===c.sessionId)!.date)} · {c.item.sets} × {metric==='reps'?`${lo}–${hi}`:lo} {metric} · {c.before} → {c.after} min</p>)}</div>}
 {error&&<p role="alert" className="notice warning">{error}</p>}
 <div className="dialog-actions"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={()=>{if(!a)return;if(needsConfig&&!convention){setError('Choose how weight is recorded first.');return}if(preview?.errors.length){setError(preview.errors.join(' '));return}setError('');if(!review){setReview(true);return}const r=applyAddition(s,a);if(r.error)setError(r.error);else onApply(r.state)}}>{review?'Accept addition to plan':'Review addition'}</Button></div>
 </>}
 </DialogContent></Dialog>
}
