"use client";
import {workoutName} from '@/lib/presentation';

import {useState} from 'react';
import {LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {Button} from '@/components/ui/button';
import {type State,exFor,requiresSetup,isLoadTracked,loadConvention} from '@/lib/training';
import {exerciseSeries,strengthIndex,volume} from '@/lib/progress';
const config={value:{label:'Recorded',color:'var(--chart-1)'},index:{label:'Strength index',color:'var(--chart-1)'},volume:{label:'Volume',color:'var(--chart-1)'}};
function DataTable({title,headers,rows}:{title:string;headers:string[];rows:(string|number)[][]}){return <details className="chart-data"><summary>{title}</summary><table><caption>{title}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No recorded values yet.</p>}</details>}
export function ProgressDashboard({state:s,onExercise,onSample}:{state:State;onExercise:(id:string)=>void;onSample:()=>void}){
 const logged=s.history.filter(w=>w.finishedAt).sort((a,b)=>a.date.localeCompare(b.date));const ids=[...new Set(logged.flatMap(w=>w.sets.filter(x=>x.done).map(x=>x.exerciseId)))];
 const [selected,setSelected]=useState(''),[metric,setMetric]=useState('load'),[setup,setSetup]=useState('');const id=ids.includes(selected)?selected:ids.includes('bench')?'bench':ids[0]||'bench',ex=exFor(id,s.custom);
 const setups=[...new Set(logged.filter(w=>w.sets.some(x=>x.exerciseId===id)).map(w=>w.loadContext?.[id]||''))];const currentSetup=setups.includes(setup)?setup:setups[0]||'';
 const factor=s.profile.units==='lb'?2.2046226218:1;
 const actualMetric=!isLoadTracked(ex)?'amount':metric==='estimated'&&(s.profile.age<18||!ex.progressionEnabled||ex.metric!=='reps')?'load':metric;
 const data=exerciseSeries(s,id,currentSetup).map(p=>({...p,value:actualMetric==='amount'?p.amount:actualMetric==='estimated'?(p.estimated===null?null:Math.round(p.estimated*factor*10)/10):(p.load===null?null:Math.round(p.load*factor*10)/10)}));
 const sessions=logged.map(w=>{const v=volume(s,w);return{id:w.id,label:new Date(w.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}),volume:v.count?Math.round(v.kg*factor):null,excluded:v.excluded,partial:w.partial,title:workoutName(w,s),date:w.date}});
 const index=strengthIndex(s),last=data.filter(p=>p.value!==null).at(-1),first=data.find(p=>p.value!==null);
 return <><div className="progress-cards"><section className="card"><p className="eyebrow">SESSIONS RECORDED</p><strong className="big-number">{logged.length}</strong><p className="muted">{logged.filter(w=>w.partial).length} partial workouts</p></section><section className="card"><p className="eyebrow">PERSONAL STRENGTH INDEX</p><strong className="big-number">{index.current??'—'}</strong><p className="muted">{index.current?`${index.current-100>=0?'+':''}${index.current-100}% from your starting baseline`:s.profile.age<18?'Available for ages 18 and over':index.basket.length===3?'Recent comparable data needed':'Log two qualifying sessions for each of three lifts'}</p></section><section className="card"><p className="eyebrow">RECORDED SETS / TASKS</p><strong className="big-number">{logged.reduce((n,w)=>n+w.sets.filter(x=>x.done).length,0)}</strong><p className="muted">Sets you marked complete</p></section></div>
 {!logged.length&&<section className="card"><h3>See what a few months can look like.</h3><p className="muted">View a sample training history with a lighter week and a plateau.</p><Button onClick={onSample}>View 12-week example</Button></section>}
 <section className="card chart-card"><div className="split"><div><p className="eyebrow">EXERCISE PROGRESS</p><h2>{ex.name}</h2></div>{last&&<div className="chart-value"><strong>{last.value}</strong><span>{actualMetric==='amount'?ex.metric:s.profile.units}{first&&last.value!==null&&first.value!==null?` · ${last.value-first.value>=0?'+':''}${Math.round((last.value-first.value)*10)/10} since first`:''}</span></div>}</div><div className="chart-controls"><label>Exercise<select aria-label="Chart exercise" value={id} onChange={e=>{setSelected(e.target.value);setSetup('')}}>{ids.length?ids.map(i=><option value={i} key={i}>{exFor(i,s.custom).name}</option>):<option value="bench">No saved exercise yet</option>}</select></label>{isLoadTracked(ex)&&<label>Measurement<select aria-label="Chart measurement" value={actualMetric} onChange={e=>setMetric(e.target.value)}><option value="load">Heaviest recorded set</option><option value="amount">Best set · {ex.metric}</option>{s.profile.age>=18&&ex.progressionEnabled&&ex.metric==='reps'&&<option value="estimated">Estimated 1RM · eligible sets</option>}</select></label>}{requiresSetup(ex)&&<label>Machine / setup<select aria-label="Chart machine setup" value={currentSetup} onChange={e=>setSetup(e.target.value)}>{setups.map(x=><option key={x} value={x}>{x||'Setup not recorded · cannot compare'}</option>)}</select></label>}</div>
 {data.some(x=>x.value!==null)?<ChartContainer config={config} className="training-chart"><LineChart data={data} margin={{top:16,right:20,left:0,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="label" minTickGap={36}/><YAxis width={44}/><Tooltip formatter={(v)=>[`${v} ${actualMetric==='amount'?ex.metric:s.profile.units}`,actualMetric==='estimated'?'Estimated 1RM':'Recorded']} contentStyle={{borderRadius:10,background:'var(--card)',color:'var(--foreground)',borderColor:'var(--input)'}}/><Line dataKey="value" type="linear" stroke="var(--chart-1)" strokeWidth={3} dot={{r:3}} connectNulls={false} isAnimationActive={false}/></LineChart></ChartContainer>:<div className="chart-empty">No recorded sets qualify for this measurement yet.</div>}
 <p className="small-copy">{loadConvention(id,s.custom)} {actualMetric==='estimated'?'Epley estimate from 1–10 reps with 0–2 reps left, no symptoms, and a completed session. A single rep shows the observed load. Submaximal estimates can understate actual capacity; this is not a tested maximum.':'Heaviest load and best repetitions are separate measurements; neither alone establishes a new maximum.'}</p><DataTable title="View exercise chart data" headers={["Date",actualMetric==='estimated'?"Estimated 1RM":actualMetric==='amount'?ex.metric:`Load (${s.profile.units})`,"Record", "Setup"]} rows={data.map(x=>[x.date,x.value??"Not available",x.partial?"Partial":"Completed",requiresSetup(ex)?currentSetup||"Unknown":"Not required"])}/><Button variant="ghost" disabled={!ids.length} onClick={()=>onExercise(id)}>View exercise history</Button></section>
 <div className="charts-grid"><section className="card chart-card"><p className="eyebrow">WORK PER SESSION</p><h2>Recorded load volume</h2><p className="muted">{s.profile.units} × repetitions · external load only</p>{sessions.some(x=>x.volume!==null)?<ChartContainer config={config} className="training-chart compact"><BarChart data={sessions}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="label" minTickGap={45}/><YAxis width={48} tickFormatter={v=>v>=1000?`${v/1000}k`:v}/><Tooltip formatter={(v,_name,item)=>[`${Number(v).toLocaleString()} ${s.profile.units} × reps`,`${item.payload?.title||'Workout'} · ${item.payload?.date||''}${item.payload?.partial?' · partial':''}`]} contentStyle={{borderRadius:10,background:'var(--card)',color:'var(--foreground)',borderColor:'var(--input)'}}/><Bar dataKey="volume" fill="var(--chart-1)" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ChartContainer>:<div className="chart-empty">Log loaded sets to see volume.</div>}<p className="small-copy">Weight × reps, counting both sides where needed. Bodyweight exercises, timed work and sets without a known weight or recording method are left out. {sessions.reduce((n,x)=>n+x.excluded,0)} sets or intervals left out. Machine totals use the recorded weight; they do not measure the work done by the machine. A higher total is not always a better workout.</p><DataTable title="View session volume data" headers={["Date","Workout",`${s.profile.units} × reps`,"Record","Excluded sets"]} rows={sessions.map(x=>[x.date,x.title,x.volume??"Not available",x.partial?"Partial":"Completed",x.excluded])}/></section>
 <section className="card chart-card"><p className="eyebrow">YOUR BASELINE = 100</p><h2>Strength over time</h2>{index.points.some(x=>x.index!==null)?<ChartContainer config={config} className="training-chart compact"><LineChart data={index.points}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="label" minTickGap={45}/><YAxis width={44} domain={['auto','auto']}/><Tooltip formatter={(v)=>[v,'Personal index']} contentStyle={{borderRadius:10,background:'var(--card)',color:'var(--foreground)',borderColor:'var(--input)'}}/><ReferenceLine y={100} stroke="var(--muted-foreground)" strokeDasharray="4 4"/><Line dataKey="index" type="linear" stroke="var(--chart-1)" strokeWidth={3} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ChartContainer>:<div className="chart-empty">{s.profile.age<18?'Adult strength estimates are disabled for youth profiles.':'Log two qualifying results for each of three lifts within a 14-day window.'}</div>}<DataTable title="View strength index data" headers={["Date","Personal index"]} rows={index.points.map(x=>[x.date,x.index??"Not available"])}/><details className="metric-method"><summary>How this index works</summary><p>Your starting level is 100. The index uses the first three qualifying non-machine lifts with two strength estimates each in a 14-day window. Each lift starts at the average of its first two estimates. Later points compare each lift’s latest estimate with that starting value, then average the three percentages. Each lift counts equally and needs a qualifying result within the past 21 days. This is an approximate progress measure, not a tested performance score or a ranking against other people. Adding older records can change your starting values.</p><p>Exercises: {index.basket.map(i=>exFor(i,s.custom).name).join(', ')||'Not established'}.</p></details></section></div>
 </>;
}
