import {useNativeAppearance,useThemedStyles} from './appearance';
import {planName,sessionName,trainingCopy} from './shared/presentation';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View,StyleSheet} from 'react-native';
import {type Profile,type Plan,type State,type Event,goals,weekdays,day,toKg,targetText,exFor,niceDate} from './shared/training';
import {planOptions,referenceOption,setupErrors,type PlanOption} from './shared/onboarding';
import {readLocalSetup,saveLocalSetup} from './storage';
import {programReferences} from './shared/program-catalog';
import {NamedPrograms} from './named-programs';
import {focusChoices} from './shared/training-focus';
const c={ink:'#19362D',green:'#214D3A',line:'#DCE1D7'};
const baseStyles=StyleSheet.create({body:{fontSize:15,lineHeight:22,color:c.ink},title:{fontSize:24,fontWeight:'700',color:c.ink},row:{flexDirection:'row',flexWrap:'wrap',gap:8},input:{fontSize:16,minHeight:48,borderWidth:1,borderColor:c.line,borderRadius:8,padding:12},button:{minHeight:48,padding:12,borderWidth:1,borderColor:c.green,borderRadius:8,justifyContent:'center'},card:{borderWidth:1,borderColor:c.line,borderRadius:12,padding:12,gap:10}});
function Choice({label,selected,onPress}:{label:string;selected?:boolean;onPress:()=>void}){ const styles=useThemedStyles(baseStyles),{colors:c}=useNativeAppearance();return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[styles.button,selected&&{backgroundColor:c.green}]}><Text style={[styles.body,selected&&{color:c.onAccent}]}>{label}</Text></Pressable>}
function Field({label,value,onChange,numeric=false}:{label:string;value:string;onChange:(v:string)=>void;numeric?:boolean}){ const styles=useThemedStyles(baseStyles);return <View style={{gap:6}}><Text style={styles.body}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} maxLength={100} keyboardType={numeric?'decimal-pad':'default'} style={styles.input}/></View>}
export function PlanSetup({state,onAccept,initialProgramId}:{state:State;initialProgramId?:string;onAccept:(profile:Profile,plan:Plan,events:Event[])=>string|undefined}){ const styles=useThemedStyles(baseStyles),{colors:c}=useNativeAppearance();
 const initialRef=programReferences.find(r=>r.id===initialProgramId);
 const initialProfile:Profile={...state.profile,start:day(),programId:undefined,goal:initialRef?.goal||state.profile.goal,mode:initialRef?'manual':state.profile.mode,weeks:Math.min(state.profile.weeks,initialRef?.weeks||12),name:state.profile.name==='Local demo'?'':state.profile.name};
 const [p,setP]=useState<Profile>(initialProfile),[step,setStep]=useState(initialRef?3:0),[selected,setSelected]=useState<PlanOption|null>(()=>initialRef?referenceOption(initialProfile,state.events,initialRef.id):null),[error,setError]=useState(()=>initialRef?referenceOption(initialProfile,state.events,initialRef.id).errors.join(' '):''),[showAll,setShowAll]=useState(false),[morePlans,setMorePlans]=useState(false),[extraWork,setExtraWork]=useState(false),[sourceDetails,setSourceDetails]=useState(false);
 const [loaded,setLoaded]=useState(!!initialRef),[saveNote,setSaveNote]=useState(initialRef?'Review this source template with your current settings. Go back to adjust them.':'Opening saved setup…');
 const accepted=useRef(false),write=useRef(0);
 // Read the external setup once; accepting the plan validates the current calendar.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(initialProgramId)return;let live=true;readLocalSetup().then(d=>{if(!live)return;if(d&&d.basePlanId===(state.plan?.id||null)){setP(d.profile);setStep(d.baseEvents===JSON.stringify(state.events)?Math.min(3,d.step):1);setSaveNote('Your saved setup is ready. Review your choices before accepting.')}else setSaveNote('Your setup will be saved on this device.');}).catch(()=>{if(live)setSaveNote('The previous setup could not be opened. Your accepted plan and workouts are unchanged.')}).finally(()=>{if(live)setLoaded(true)});return()=>{live=false}},[]);
 useEffect(()=>{if(!loaded||accepted.current)return;const version=++write.current;let live=true;Promise.resolve().then(()=>saveLocalSetup({schema:1,basePlanId:state.plan?.id||null,baseEvents:JSON.stringify(state.events),profile:p,events:state.events,step})).then(()=>{if(live&&version===write.current)setSaveNote('Setup saved on this device. You can close and continue later.')}).catch(()=>{if(live&&version===write.current)setSaveNote('Setup could not be saved. Keep it open to finish, or try again.')});return()=>{live=false}},[p,step,loaded,state.plan?.id,state.events]);
 const options=useMemo(()=>step===3?planOptions(p,state.events):[],[step,p,state.events]);
 const set=(key:keyof Profile,value:unknown)=>{setP(v=>({...v,[key]:value,programId:undefined}));setSelected(null);setError('')};
 const next=()=>{const errors=(step===0?[0]:step===1?[3]:[2,4]).flatMap(i=>setupErrors(p,i));if(errors.length){setError(errors.join(' '));return}setError('');setStep(step+1)};
 if(!loaded)return <Text style={styles.body}>Opening saved setup…</Text>;
 return <View style={{gap:16}}><Text style={styles.title}>{['Your goal','Your schedule','Equipment and coaching','Choose your plan'][step]}</Text><Text style={styles.body}>Step {step+1} of 4</Text><Text accessibilityLiveRegion="polite" style={styles.body}>{saveNote}</Text>
 {step===0&&<><Field label="Profile name" value={p.name} onChange={v=>set('name',v)}/><Field label="Age" numeric value={String(p.age||'')} onChange={v=>set('age',Number(v))}/><Text style={styles.body}>Main goal</Text><View style={styles.row}>{goals.map(([id,label])=><Choice key={id} label={label} selected={p.goal===id} onPress={()=>set('goal',id)}/>)}</View>{p.goal==='sport'&&<><Field label="Sport" value={p.sport} onChange={v=>set('sport',v)}/><Field label="Position or event" value={p.position} onChange={v=>set('position',v)}/><Text style={styles.body}>Available sport plans develop general foundations. They do not yet provide position-specific training.</Text></>}<Text style={styles.body}>Experience</Text>{['First time','Some experience','Experienced'].map(x=><Choice key={x} label={x} selected={p.experience===x} onPress={()=>set('experience',x)}/>)}{p.experience==='Experienced'&&<Choice label="I have at least 8 recent weeks of steady training" selected={!!p.establishedTraining} onPress={()=>set('establishedTraining',!p.establishedTraining)}/>}<View style={styles.row}>{(['lb','kg'] as const).map(x=><Choice key={x} label={x} selected={p.units===x} onPress={()=>set('units',x)}/>)}</View></>}
 {step===1&&<><Field label="Start date · YYYY-MM-DD" value={p.start} onChange={v=>set('start',v)}/><Field label="Training weeks · 2–12" numeric value={String(p.weeks||'')} onChange={v=>set('weeks',Number(v))}/><Field label="Minutes per session · 15–120" numeric value={String(p.minutes||'')} onChange={v=>set('minutes',Number(v))}/><Text style={styles.body}>Days you can train</Text><View style={styles.row}>{weekdays.map((label,i)=><Choice key={label} label={label} selected={p.days.includes(i)} onPress={()=>set('days',p.days.includes(i)?p.days.filter(d=>d!==i):[...p.days,i].sort())}/>)}</View><Text style={styles.body}>Your saved commitments are included. Review every date before starting.</Text></>}
 {step===2&&<><Text style={styles.body}>Available equipment</Text>{['Full gym','Dumbbells','Bodyweight + band','No equipment'].map(x=><Choice key={x} label={x} selected={p.equipment===x} onPress={()=>set('equipment',x)}/>)}{['Full gym','Dumbbells'].includes(p.equipment)&&<Field label={`Heaviest ONE dumbbell (${p.units}) · optional`} numeric value={p.dumbbellMaxKg===undefined?'':String(Math.round(p.dumbbellMaxKg*(p.units==='lb'?2.2046226218:1)*100)/100)} onChange={v=>set('dumbbellMaxKg',v===''?undefined:toKg(Number(v),p.units))}/>}<Choice label="Standing or seated exercises only" selected={!!p.noFloor} onPress={()=>set('noFloor',!p.noFloor)}/><Text style={styles.body}>Who leads training?</Text>{[['app','Guide me with a plan'],['coach','Track my coach’s plan'],['manual','Write my own plan']].map(([id,label])=><Choice key={id} label={label} selected={p.mode===id} onPress={()=>set('mode',id)}/>)}{(p.age<18||p.focuses?.includes('jumping'))&&<Choice label="Qualified supervision is available" selected={p.supervision} onPress={()=>set('supervision',!p.supervision)}/>}<Choice label={extraWork?'Hide optional extra work':'Optional extra work'} onPress={()=>setExtraWork(v=>!v)}/>{extraWork&&<>{focusChoices.map(f=><View key={f.id}><Choice label={f.title} selected={p.focuses?.includes(f.id)} onPress={()=>set('focuses',p.focuses?.includes(f.id)?p.focuses.filter(x=>x!==f.id):[...(p.focuses||[]),f.id])}/><Text style={styles.body}>{f.description}</Text></View>)}{p.focuses?.includes('jumping')&&<Choice label="Clear landing area and comfortable landing skill" selected={p.jumpReady} onPress={()=>set('jumpReady',!p.jumpReady)}/>}<Text style={styles.body}>The preview checks whether this extra work fits your time, equipment and recovery needs. Age and supervision requirements also apply.</Text></>}<Text style={styles.body}>Season</Text><View style={styles.row}>{['Off-season','Preseason','In-season','Transition / recovery'].map(x=><Choice key={x} label={x} selected={p.season===x} onPress={()=>set('season',x)}/>)}</View>{['running','hybrid'].includes(p.goal)&&<><Choice label="I already run 30 minutes comfortably" selected={!!p.runBase} onPress={()=>set('runBase',!p.runBase)}/><Field label="Recent running days each week" numeric value={String(p.runDays??0)} onChange={v=>set('runDays',Number(v))}/><Field label="Recent easy running minutes each week" numeric value={String(p.runMinutes??0)} onChange={v=>set('runMinutes',Number(v))}/></>}</>}
 {step===3&&<>{!options.some(o=>o.plan&&o.profile.mode===p.mode&&o.profile.goal===p.goal)&&<View><Text style={styles.body}>No plan in your selected mode fits these choices. Go back to adjust time, days or equipment, or use your own tracking schedule.</Text>{[...new Set(options.filter(o=>!o.plan&&o.profile.mode===p.mode&&o.profile.goal===p.goal).flatMap(o=>o.errors))].slice(0,5).map(e=><Text style={styles.body} key={e}>{e}</Text>)}</View>}{options.filter(o=>o.plan).filter((o,i)=>morePlans||i<3||selected?.id===o.id).map(o=><View key={o.id} style={styles.card}><Text style={styles.title}>{o.plan?planName(o.plan):o.title}</Text><Text style={styles.body}>{o.description}</Text><Text style={styles.body}>{o.plan!.sessions.length} sessions · ends {niceDate(o.plan!.sessions.at(-1)!.date)}</Text><Choice label={selected?.id===o.id?'Selected':'Review this plan'} selected={selected?.id===o.id} onPress={()=>{setSelected(o);setShowAll(false)}}/></View>)}{options.filter(o=>o.plan).length>3&&<Choice label={morePlans?'Show fewer plans':'See more plans'} onPress={()=>setMorePlans(v=>!v)}/>} <NamedPrograms profile={p} events={state.events} selectedId={selected?.id} onSelect={o=>{setSelected(o.plan?o:null);setShowAll(false);setError(o.errors.join(' '))}}/> {selected?.plan&&<View style={styles.card}><Text style={styles.title}>Review {planName(selected.plan)}</Text>{selected.plan.sessions.filter(x=>showAll||x.id===selected.plan!.sessions[0].id).map(x=><View key={x.id}><Text style={[styles.body,{fontWeight:'700'}]}>{niceDate(x.date)} · {sessionName(x,selected.plan)} · {x.minutes} min</Text>{x.items.map(i=><View key={i.exerciseId}><Text style={styles.body}>{exFor(i.exerciseId).name} · {i.sets} × {targetText(i)} · {i.rest}s rest</Text>{i.note&&<Text style={styles.body}>{i.note}</Text>}</View>)}</View>)}<Choice label={showAll?'Show one workout':'Show all workouts'} onPress={()=>setShowAll(!showAll)}/><Text style={styles.body}>{trainingCopy(selected.plan.progression)}</Text>{selected.profile.programId?.startsWith('ref-')&&<><Choice label={sourceDetails?'Hide source requirements and variations':'Source requirements and variations'} onPress={()=>setSourceDetails(v=>!v)}/>{sourceDetails&&selected.plan.notes.map(n=><Text key={n} style={styles.body}>{n}</Text>)}</>}{selected.plan.notes.filter(n=>n.startsWith('[Focus]')).map(n=><Text key={n} style={styles.body}>{n}</Text>) }{selected.plan.notes.filter(n=>n.startsWith('Days off')||n.startsWith('Competition')).map(n=><Text style={styles.body} key={n}>{n}</Text>)}<Choice label="Start this plan" onPress={()=>{const message=onAccept(selected.profile,selected.plan!,state.events);if(message)setError(message);else{accepted.current=true}}}/></View>}</>}
 {!!error&&<Text accessibilityRole="alert" style={[styles.body,{color:c.danger}]}>{error}</Text>}<View style={styles.row}>{step>0&&<Choice label="Back" onPress={()=>{setStep(step-1);setError('')}}/>}{step<3&&<Choice label={step===2?'See my plans':'Continue'} onPress={next}/>}</View>
 </View>
}
