import {useNativeAppearance,useThemedStyles} from './appearance';
import {planName,sessionName,trainingCopy} from './shared/presentation';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Pressable,ScrollView,Text,TextInput,View,StyleSheet} from 'react-native';
import {type Profile,type Plan,type State,type Event,goals,weekdays,day,toKg,targetText,exFor,niceDate} from './shared/training';
import {planOptions,setupErrors,setupStartProfile,type PlanOption} from './shared/onboarding';
import {clearLocalSetup,readLocalSetup,saveLocalSetup} from './storage';
import {focusChoices} from './shared/training-focus';
const c={ink:'#19362D',green:'#214D3A',line:'#DCE1D7'};
const baseStyles=StyleSheet.create({body:{fontSize:16,lineHeight:24,color:c.ink},title:{fontSize:24,fontWeight:'700',color:c.ink},row:{flexDirection:'row',flexWrap:'wrap',gap:8},input:{fontSize:16,minHeight:48,borderWidth:1,borderColor:c.line,borderRadius:8,padding:12},button:{minHeight:48,padding:12,borderWidth:1,borderColor:c.green,borderRadius:8,justifyContent:'center'},card:{borderWidth:1,borderColor:c.line,borderRadius:12,padding:16,gap:12},notice:{borderWidth:1,borderColor:c.line,borderRadius:12,padding:12,gap:8}});
function Choice({label,selected,onPress}:{label:string;selected?:boolean;onPress:()=>void}){ const styles=useThemedStyles(baseStyles),{colors:c}=useNativeAppearance();return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={[styles.button,selected&&{backgroundColor:c.green}]}><Text style={[styles.body,selected&&{color:c.onAccent}]}>{label}</Text></Pressable>}
// The one filled action on this screen: accepting a plan.
function Primary({label,onPress}:{label:string;onPress:()=>void}){ const styles=useThemedStyles(baseStyles),{colors:c}=useNativeAppearance();return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.button,{backgroundColor:c.green}]}><Text style={[styles.body,{color:c.onAccent,fontWeight:'700'}]}>{label}</Text></Pressable>}
function Field({label,value,onChange,numeric=false,placeholder}:{label:string;value:string;onChange:(v:string)=>void;numeric?:boolean;placeholder?:string}){ const styles=useThemedStyles(baseStyles),{colors:c}=useNativeAppearance();return <View style={{gap:6}}><Text style={styles.body}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={c.muted} maxLength={100} keyboardType={numeric?'decimal-pad':'default'} style={styles.input}/></View>}
export function PlanSetup({state,onAccept,scrollRef}:{state:State;onAccept:(profile:Profile,plan:Plan,events:Event[])=>string|undefined;scrollRef?:React.RefObject<ScrollView|null>}){ const styles=useThemedStyles(baseStyles),{colors:c}=useNativeAppearance();
 const [p,setP]=useState<Profile>(()=>setupStartProfile(state.profile,day())),[step,setStep]=useState(0),[selected,setSelected]=useState<PlanOption|null>(null),[error,setError]=useState(''),[showAll,setShowAll]=useState(false),[confirmReplace,setConfirmReplace]=useState(false);
 const [loaded,setLoaded]=useState(false),[saveNote,setSaveNote]=useState('Opening saved setup…');
 const accepted=useRef(false),write=useRef(0),cardY=useRef<Record<string,number>>({});
 useEffect(()=>{let live=true;readLocalSetup().then(d=>{if(!live)return;if(d&&d.basePlanId===(state.plan?.id||null)){setP(d.profile);setStep(d.baseEvents===JSON.stringify(state.events)?Math.min(3,d.step):1);setSaveNote('Your saved setup is ready. Review your choices before accepting.')}else setSaveNote('Your setup will be saved on this device.');}).catch(()=>{if(live)setSaveNote('The previous setup could not be opened. Your accepted plan and workouts are unchanged.')}).finally(()=>{if(live)setLoaded(true)});return()=>{live=false}},[]);
 useEffect(()=>{if(!loaded||accepted.current)return;const version=++write.current;let live=true;Promise.resolve().then(()=>saveLocalSetup({schema:1,basePlanId:state.plan?.id||null,baseEvents:JSON.stringify(state.events),profile:p,events:state.events,step})).then(()=>{if(live&&version===write.current)setSaveNote('Setup saved on this device. You can close and continue later.')}).catch(()=>{if(live&&version===write.current)setSaveNote('Setup could not be saved. Keep it open to finish, or try again.')});return()=>{live=false}},[p,step,loaded,state.plan?.id,state.events]);
 const options=useMemo(()=>step===3?planOptions(p,state.events):[],[step,p,state.events]);
 const set=(key:keyof Profile,value:unknown)=>{setP(v=>({...v,[key]:value,programId:undefined}));setSelected(null);setConfirmReplace(false);setError('')};
 const next=()=>{const errors=(step===0?[0]:step===1?[3]:[2,4]).flatMap(i=>setupErrors(p,i));if(errors.length){setError(errors.join(' '));return}setError('');setStep(step+1)};
 // Choosing a plan opens its review under the card, and brings that card to the top of the screen.
 const choose=(o:PlanOption)=>{setSelected(o);setShowAll(false);setConfirmReplace(false);setError('');scrollRef?.current?.scrollTo({y:Math.max(0,(cardY.current[o.id]??0)+8),animated:false})};
 const startPlan=()=>{const plan=selected?.plan;if(!selected||!plan||accepted.current)return;const message=onAccept(selected.profile,plan,state.events);if(message){setError(message);setConfirmReplace(false);return}accepted.current=true;void clearLocalSetup().catch(()=>undefined)};
 // A plan already exists, so accepting a new one replaces it. Ask first.
 const requestStart=()=>{if(state.plan){setConfirmReplace(true);return}startPlan()};
 if(!loaded)return <Text style={styles.body}>Opening saved setup…</Text>;
 const current=state.plan?planName(state.plan):'';
 return <View style={{gap:16}}><Text style={styles.title}>{['Your goal','Your schedule','Equipment and coaching','Choose your plan'][step]}</Text><Text style={styles.body}>Step {step+1} of 4</Text><Text accessibilityLiveRegion="polite" style={styles.body}>{saveNote}</Text>
 {step===0&&<><Field label="Profile name" placeholder="e.g. Alex" value={p.name} onChange={v=>set('name',v)}/><Field label="Age" numeric placeholder="14–100" value={String(p.age||'')} onChange={v=>set('age',Number(v))}/><Text style={styles.body}>Main goal</Text><View style={styles.row}>{goals.map(([id,label])=><Choice key={id} label={label} selected={p.goal===id} onPress={()=>set('goal',id)}/>)}</View>{p.goal==='sport'&&<><Field label="Sport" value={p.sport} onChange={v=>set('sport',v)}/><Field label="Position or event" value={p.position} onChange={v=>set('position',v)}/><Text style={styles.body}>Available sport plans develop general foundations. They do not yet provide position-specific training.</Text></>}<Text style={styles.body}>Experience</Text>{['First time','Some experience','Experienced'].map(x=><Choice key={x} label={x} selected={p.experience===x} onPress={()=>set('experience',x)}/>)}{p.experience==='Experienced'&&<Choice label="I have at least 8 recent weeks of steady training" selected={!!p.establishedTraining} onPress={()=>set('establishedTraining',!p.establishedTraining)}/>}<View style={styles.row}>{(['lb','kg'] as const).map(x=><Choice key={x} label={x} selected={p.units===x} onPress={()=>set('units',x)}/>)}</View></>}
 {step===1&&<><Field label="Start date · YYYY-MM-DD" value={p.start} onChange={v=>set('start',v)}/><Field label="Training weeks · 2–12" numeric value={String(p.weeks||'')} onChange={v=>set('weeks',Number(v))}/><Field label="Minutes per session · 15–120" numeric value={String(p.minutes||'')} onChange={v=>set('minutes',Number(v))}/><Text style={styles.body}>Days you can train</Text><View style={styles.row}>{weekdays.map((label,i)=><Choice key={label} label={label} selected={p.days.includes(i)} onPress={()=>set('days',p.days.includes(i)?p.days.filter(d=>d!==i):[...p.days,i].sort())}/>)}</View><Text style={styles.body}>Your saved commitments are included. Review every date before starting.</Text></>}
 {step===2&&<><Text style={styles.body}>Available equipment</Text>{['Full gym','Dumbbells','Bodyweight + band','No equipment'].map(x=><Choice key={x} label={x} selected={p.equipment===x} onPress={()=>set('equipment',x)}/>)}{['Full gym','Dumbbells'].includes(p.equipment)&&<Field label={`Heaviest ONE dumbbell (${p.units}) · optional`} numeric value={p.dumbbellMaxKg===undefined?'':String(Math.round(p.dumbbellMaxKg*(p.units==='lb'?2.2046226218:1)*100)/100)} onChange={v=>set('dumbbellMaxKg',v===''?undefined:toKg(Number(v),p.units))}/>}<Choice label="Standing or seated exercises only" selected={!!p.noFloor} onPress={()=>set('noFloor',!p.noFloor)}/><Text style={styles.body}>Who leads training?</Text>{[['app','Guide me with a plan'],['coach','Track my coach’s plan'],['manual','Write my own plan']].map(([id,label])=><Choice key={id} label={label} selected={p.mode===id} onPress={()=>set('mode',id)}/>)}{(p.age<18||p.focuses?.includes('jumping'))&&<Choice label="Qualified supervision is available" selected={p.supervision} onPress={()=>set('supervision',!p.supervision)}/>}<Text style={styles.body}>Optional extra work</Text>{focusChoices.map(f=><View key={f.id}><Choice label={f.title} selected={p.focuses?.includes(f.id)} onPress={()=>set('focuses',p.focuses?.includes(f.id)?p.focuses.filter(x=>x!==f.id):[...(p.focuses||[]),f.id])}/><Text style={styles.body}>{f.description}</Text></View>)}{p.focuses?.includes('jumping')&&<Choice label="Clear landing area and comfortable landing skill" selected={p.jumpReady} onPress={()=>set('jumpReady',!p.jumpReady)}/>}<Text style={styles.body}>The preview checks whether this extra work fits your time, equipment and recovery needs. Age and supervision requirements also apply.</Text><Text style={styles.body}>Season</Text><View style={styles.row}>{['Off-season','Preseason','In-season','Transition / recovery'].map(x=><Choice key={x} label={x} selected={p.season===x} onPress={()=>set('season',x)}/>)}</View>{['running','hybrid'].includes(p.goal)&&<><Choice label="I already run 30 minutes comfortably" selected={!!p.runBase} onPress={()=>set('runBase',!p.runBase)}/><Field label="Recent running days each week" numeric value={String(p.runDays??0)} onChange={v=>set('runDays',Number(v))}/><Field label="Recent easy running minutes each week" numeric value={String(p.runMinutes??0)} onChange={v=>set('runMinutes',Number(v))}/></>}</>}
 {step===3&&<>
  {state.active&&<View style={styles.notice} accessibilityRole="alert"><Text style={styles.body}>Finish or save your current workout before accepting a new plan.</Text></View>}
  {state.plan&&!state.active&&<View style={styles.notice}><Text style={styles.body}>Your current plan is {current}. Accepting a new plan replaces it. The current plan moves to Saved & previous, and completed workouts stay in History.</Text></View>}
  {!options.some(o=>o.plan&&o.profile.mode===p.mode&&o.profile.goal===p.goal)&&<View><Text style={styles.body}>No plan in your selected mode fits these choices. Go back to adjust time, days or equipment, or use your own tracking schedule.</Text>{[...new Set(options.filter(o=>!o.plan&&o.profile.mode===p.mode&&o.profile.goal===p.goal).flatMap(o=>o.errors))].slice(0,5).map(e=><Text style={styles.body} key={e}>{e}</Text>)}</View>}
  {options.filter(o=>o.plan).map(o=>{const isSel=selected?.id===o.id,plan=o.plan!;return <View key={o.id} onLayout={e=>{cardY.current[o.id]=e.nativeEvent.layout.y}} style={[styles.card,isSel&&{borderWidth:2,borderColor:c.green}]}>
   <Text style={styles.title}>{planName(plan)}</Text>
   <Text style={styles.body}>{o.description}</Text>
   <Text style={styles.body}>{plan.sessions.length} sessions · ends {niceDate(plan.sessions.at(-1)!.date)}</Text>
   {!isSel&&<Choice label="Choose this plan" onPress={()=>choose(o)}/>}
   {isSel&&<>
    <Text style={styles.body}>{trainingCopy(plan.progression)}</Text>
    <Primary label="Start this plan" onPress={requestStart}/>
    {!!error&&<Text accessibilityRole="alert" style={[styles.body,{color:c.danger}]}>{error}</Text>}
    {confirmReplace&&<View style={styles.notice} accessibilityRole="alert"><Text style={[styles.title,{fontSize:20}]}>Replace your current plan?</Text><Text style={styles.body}>{current} moves to Saved & previous. Its completed workouts and history stay as they are. Its future sessions stop showing on Today.</Text><Primary label="Replace with this plan" onPress={startPlan}/><Choice label="Keep current plan" onPress={()=>setConfirmReplace(false)}/></View>}
    <Text style={[styles.body,{fontWeight:'700'}]}>{showAll?'All workouts':'First week'}</Text>
    {plan.sessions.filter(x=>showAll||x.week===1).map(x=><View key={x.id}><Text style={[styles.body,{fontWeight:'700'}]}>{niceDate(x.date)} · {sessionName(x,plan)} · {x.minutes} min</Text>{x.items.map(i=><Text style={styles.body} key={i.exerciseId}>{exFor(i.exerciseId).name} · {i.sets} × {targetText(i)}</Text>)}</View>)}
    <Choice label={showAll?'Show first week':'Show all workouts'} onPress={()=>setShowAll(!showAll)}/>
    {plan.notes.filter(n=>n.startsWith('[Focus]')).map(n=><Text key={n} style={styles.body}>{n}</Text>)}
    {plan.notes.filter(n=>n.startsWith('Days off')||n.startsWith('Competition')).map(n=><Text style={styles.body} key={n}>{n}</Text>)}
   </>}
  </View>})}
 </>}
 {step<3&&!!error&&<Text accessibilityRole="alert" style={[styles.body,{color:c.danger}]}>{error}</Text>}
 <View style={styles.row}>{step>0&&<Choice label="Back" onPress={()=>{setStep(step-1);setError('');setConfirmReplace(false)}}/>}{step<3&&<Choice label={step===2?'See my plans':'Continue'} onPress={next}/>}</View>
 </View>
}
