import {useThemedStyles} from './appearance';
import {sessionName} from './shared/presentation';
import React,{useState} from 'react';
import {View,Text,TextInput,Pressable,StyleSheet} from 'react-native';
import {type State,type Item,exercises,exFor,matchesExercise,niceDate} from './shared/training';
import {type TrackingEdit,previewTrackingEdit} from './shared/tracking';
const baseStyles=StyleSheet.create({body:{fontSize:16,lineHeight:24,color:'#19362D'},input:{fontSize:16,padding:12,minHeight:48,borderWidth:1,borderColor:'#DCE1D7',borderRadius:8},button:{padding:12,minHeight:48,borderRadius:8,backgroundColor:'#E6EDDD',justifyContent:'center'},row:{flexDirection:'row',flexWrap:'wrap',gap:8},card:{gap:8,padding:12,borderWidth:1,borderColor:'#DCE1D7',borderRadius:10}});
function Button({label,onPress}:{label:string;onPress:()=>void}){ const styles=useThemedStyles(baseStyles);return <Pressable accessibilityRole="button" style={styles.button} onPress={onPress}><Text style={styles.body}>{label}</Text></Pressable>}
export function SessionEditor({state,sessionId,onSave}:{state:State;sessionId:string;onSave:(edit:TrackingEdit)=>string|undefined}){ const styles=useThemedStyles(baseStyles);
 const session=state.plan!.sessions.find(x=>x.id===sessionId)!;
 const [base]=useState({planId:state.plan!.id,version:state.plan!.version,sessionId});
 const [items,setItems]=useState<Item[]>(session.items.map(i=>({...i}))),[search,setSearch]=useState(''),[exercise,setExercise]=useState(''),[sets,setSets]=useState('2'),[amount,setAmount]=useState('8'),[rest,setRest]=useState('90'),[editIndex,setEditIndex]=useState<number|null>(null),[repeatWeekday,setRepeatWeekday]=useState(false),[allowLonger,setAllowLonger]=useState(false),[message,setMessage]=useState('');
 const library=[...exercises,...state.custom],edit={...base,items,allowLonger,repeatWeekday},preview=previewTrackingEdit(state,edit);
 const add=()=>{const selected=library.find(x=>x.id===exercise);if(!selected){setMessage('Choose an exercise first.');return}const item:Item={exerciseId:exercise,sets:Number(sets),reps:Number(amount),rest:Number(rest),kg:null};if(!Number.isInteger(item.sets)||item.sets<1||item.sets>20||!Number.isFinite(item.reps)||item.reps<=0||item.reps>999||selected.metric==='reps'&&!Number.isInteger(item.reps)||!Number.isFinite(item.rest)||item.rest<0||item.rest>3600){setMessage('Enter 1–20 sets, a positive target up to 999, and 0–3,600 seconds rest. Reps must be whole numbers.');return}if(items.some((i,n)=>n!==editIndex&&i.exerciseId===exercise)){setMessage('This exercise is already listed. Edit its targets instead.');return}if(items.length>=100&&editIndex===null){setMessage('This workout already has 100 exercises.');return}setItems(v=>editIndex===null?[...v,item]:v.map((x,n)=>n===editIndex?item:x));setEditIndex(null);setExercise('');setMessage('');};
 const move=(n:number,delta:number)=>{if(n+delta<0||n+delta>=items.length)return;setItems(v=>{const next=v.slice();[next[n],next[n+delta]]=[next[n+delta],next[n]];return next})};
 return <View style={{gap:16}}><Text style={styles.body}>Enter the exercises and targets from your plan or coach. Dates and saved workouts stay the same.</Text>{items.map((i,n)=><View key={i.exerciseId} style={styles.card}><Text style={styles.body}>{n+1}. {exFor(i.exerciseId,state.custom).name} · {i.sets} × {i.reps} {exFor(i.exerciseId,state.custom).metric} · {i.rest}s rest</Text><View style={styles.row}><Button label="Edit" onPress={()=>{setEditIndex(n);setExercise(i.exerciseId);setSets(String(i.sets));setAmount(String(i.reps));setRest(String(i.rest));setMessage('')}}/><Button label="Remove" onPress={()=>{setItems(v=>v.filter((_,x)=>x!==n));setEditIndex(null);setExercise('')}}/>{n>0&&<Button label="Move up" onPress={()=>move(n,-1)}/>} {n<items.length-1&&<Button label="Move down" onPress={()=>move(n,1)}/>}</View></View>)}<Text style={styles.body}>{editIndex===null?'Add an exercise':'Edit targets'}</Text><TextInput accessibilityLabel="Find an exercise for this workout" style={styles.input} placeholder="Search name or movement" value={search} onChangeText={setSearch} maxLength={200}/>{!exercise&&library.filter(e=>matchesExercise(e,search)).slice(0,12).map(e=><Button key={e.id} label={e.name+' · '+e.equipment} onPress={()=>{setExercise(e.id);setAmount(e.metric==='reps'?'8':e.metric==='seconds'?'30':'10')}}/>)}{exercise&&<><Text style={styles.body}>{exFor(exercise,state.custom).name} · {exFor(exercise,state.custom).loadConvention}</Text>{[['Sets',sets,setSets],[`Target ${exFor(exercise,state.custom).metric}`,amount,setAmount],['Rest seconds',rest,setRest]].map(([label,value,set])=><View key={label as string}><Text style={styles.body}>{label as string}</Text><TextInput accessibilityLabel={label as string} style={styles.input} keyboardType="decimal-pad" value={value as string} onChangeText={set as (v:string)=>void} maxLength={8}/></View>)}<Button label={editIndex===null?'Add these targets':'Keep edited targets'} onPress={add}/><Button label="Cancel exercise edit" onPress={()=>{setExercise('');setEditIndex(null)}}/></>}<Text style={styles.body}>Estimated session: {preview.minutes} min · available: {state.plan!.profile.minutes} min</Text>{preview.minutes>state.plan!.profile.minutes&&<Button label={allowLonger?'Extra time accepted':'Accept this longer session'} onPress={()=>setAllowLonger(!allowLonger)}/>}<Button label={repeatWeekday?'Scope: this and future workouts on the same weekday':'Scope: this workout only'} onPress={()=>setRepeatWeekday(!repeatWeekday)}/><Text style={styles.body}>{preview.sessions.length} workouts will use these targets:</Text>{preview.sessions.map(s=><Text key={s.id} style={styles.body}>{niceDate(s.date)} · {sessionName(s,state.plan)}</Text>)}<Button label="Save workout targets" onPress={()=>{if(exercise){setMessage('Keep or cancel your exercise edit before saving the workout.');return}setMessage(onSave(edit)||'')}}/>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}</View>;
}
