import React, {type ComponentType} from 'react';
import {Pressable, Text, TextInput, View, type ViewStyle, type TextStyle} from 'react-native';
import {loadSuggestion,displayLoad,isLoadTracked,exFor,targetText,toKg,type Exercise,type Item,type State,type Workout,type SetLog,type SetMetrics} from './shared/training';
import {changeWorkoutSet,workoutSetReference,setExerciseNotes,type WorkoutSetReference} from './shared/workout-log';
import {completedSetError} from './shared/rest-timer';
import {substitutionOptions} from './shared/substitutions';
import {trainingCopy} from './shared/presentation';

type UI={
  Button:ComponentType<{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}>;
  Card:ComponentType<{children:React.ReactNode;dark?:boolean;grow?:boolean}>;
  NumericField:ComponentType<{value:number|null;onChange:(value:number|null)=>void;label:string;max:number;min?:number;nullable?:boolean;integer?:boolean;placeholder?:string}>;
  OptionalSetDetails:ComponentType<{set:SetLog;name:string;metric:string;onChange:(metrics:SetMetrics)=>void}>;
};
type Props={state:State;record:Workout;target:Item;onUpdate:(fn:(current:State)=>State)=>boolean;onLog:(reference:WorkoutSetReference,seconds:number)=>void;onNext:()=>void;editing?:boolean;ui:UI;styles:Record<string,ViewStyle&TextStyle>;colors:{muted:string;green:string;onAccent:string};onGuide:(exercise:Exercise)=>void;onError:(message:string)=>void;onSubstitute:(sessionId:string,exerciseId:string)=>void};

export function WorkoutExerciseFields({state,record,target,onUpdate,onLog,onNext,editing=false,ui,styles,colors,onGuide,onError,onSubstitute}:Props){
  const {Button,Card,NumericField,OptionalSetDetails}=ui;
  const changeSet=(reference:WorkoutSetReference,patch:Partial<SetLog>)=>onUpdate(current=>changeWorkoutSet(current,reference,patch));
  const e = exFor(target.exerciseId,state.custom),tracked = isLoadTracked(e);
  return <Card key={target.exerciseId}><View style={styles.row}><Text style={[styles.sectionTitle, styles.flex]}>{e.name}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Open ${e.name} guide`} onPress={() => onGuide(e)} style={styles.inlineAction}><Text style={styles.link}>Guide</Text></Pressable></View><Text style={styles.body}>{target.reps>0?`Target: ${target.sets} × ${targetText(target)} ${e.metric} · rest ${target.rest}s`:`${target.sets} sets · target not recorded. Enter what you completed.`}</Text><Text style={styles.small}>{e.loadConvention}</Text>
          {!editing&&isLoadTracked(e)&&<Text style={styles.small}>{(()=>{const a=loadSuggestion({...state,loadContext:{...state.loadContext,...record.loadContext}},target);return (a.kg===null?'Choose a manageable available load. ':displayLoad(a.kg,state.profile.units)+' · ')+a.reason})()}</Text>}{e.requiresSetup && <TextInput style={styles.input} placeholder="Machine / attachment / seat setting" placeholderTextColor={colors.muted} accessibilityLabel={`${e.name} machine setup`} value={record.loadContext?.[e.id] ?? ''} maxLength={200} editable={!record.sets.some(x=>x.exerciseId===e.id&&x.done)} onChangeText={text => onUpdate(s => ({ ...s, incrementKg:{...s.incrementKg,[e.id]:0}, active: { ...s.active!, loadContext: { ...s.active!.loadContext, [e.id]: text } } }))} />}
          <Text style={styles.small}>Record each completed set. Reps left (RIR) is optional: 0 means none left with good form.</Text>
          {record.sets.map((set,index)=>set.exerciseId===e.id&&<View key={`${record.id}-${index}`} style={styles.setBlock}>
          <Text style={styles.rowTitle}>Set {set.set}</Text><View style={styles.setFields}>
          <View style={styles.setField}><Text style={styles.small}>Actual {e.metric}</Text><NumericField label={`${e.name} set ${set.set} actual ${e.metric}`} value={set.reps} max={9999} placeholder={e.metric === 'reps' ? targetText(target) : undefined} onChange={n => changeSet(workoutSetReference(record,set), { reps: n ?? 0, done: false })} /></View>{tracked && <View style={styles.setField}><Text style={styles.small}>Load ({state.profile.units})</Text><NumericField label={`${e.name} set ${set.set} actual load ${state.profile.units}`} nullable value={set.kg === null ? null : set.kg * (state.profile.units === 'lb' ? 2.2046226218 : 1)} max={state.profile.units === 'lb' ? 3306 : 1500} onChange={n => changeSet(workoutSetReference(record,set), { kg: n === null ? null : toKg(n, state.profile.units), done: false })} /></View>}<View style={styles.setField}><Text style={styles.small}>Reps left · 0–5</Text><NumericField label={`${e.name} set ${set.set} reps left, RIR 0 to 5`} nullable integer max={5} value={set.rir ?? null} placeholder="RIR" onChange={n => changeSet(workoutSetReference(record,set), { rir: n ?? undefined })} /></View></View><Pressable accessibilityRole="button" disabled={set.done} accessibilityState={{disabled:set.done}} accessibilityLabel={`${set.done?'Saved':'Log'} ${e.name} set ${set.set}`} onPress={()=>{if(set.done)return;const error=completedSetError(set.reps,set.kg,e.metric);if(error){onError(error);return}onLog(workoutSetReference(record,set),target.rest);}} style={[styles.check,styles.setLogAction,set.done&&styles.checkDone]}><Text style={{color:set.done?colors.onAccent:colors.green,fontSize:14,fontWeight:'700'}}>{set.done?`Set ${set.set} saved`:`Log set ${set.set}`}</Text></Pressable>{set.done&&<Button secondary label={`Undo saved set ${set.set}`} onPress={()=>changeSet(workoutSetReference(record,set),{done:false})}/>}<OptionalSetDetails set={set} name={e.name} metric={e.metric} onChange={metrics => changeSet(workoutSetReference(record,set), { metrics })} /></View>)}
          <View style={{ gap: 6 }}><Text style={styles.small}>Notes for {e.name}</Text><TextInput accessibilityLabel={`${e.name} notes`} style={[styles.input, { minHeight: 64, textAlignVertical: 'top' }]} placeholder="Setup, how it felt, or anything to check next time" placeholderTextColor={colors.muted} multiline maxLength={1000} value={record.details?.[e.id]?.notes ?? ''} onChangeText={notes => onUpdate(s => setExerciseNotes(s, e.id, notes))} /></View>
          {target.note && <Text style={styles.small}>{trainingCopy(target.note)}</Text>}{!editing&&substitutionOptions(e.id).length>0&&<Button label="Choose a substitute" secondary onPress={()=>onSubstitute(record.sessionId,e.id)}/>}
        <Button label="Next exercise" secondary onPress={onNext}/></Card>;
}
