const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const cache=new Map();function load(name){if(cache.has(name))return cache.get(name).exports;const module={exports:{}};cache.set(name,module);const code=ts.transpileModule(fs.readFileSync(path.join('lib',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText;new Function('require','module','exports',code)(s=>s.startsWith('./')?s.endsWith('.json')?JSON.parse(fs.readFileSync(path.join('lib',s),'utf8')):load(s.slice(2)):require(s),module,module.exports);return module.exports;}
const T=load('training'),C=load('customize'),S=load('saved-data'),O=load('onboarding');let count=0;function test(n,f){f();count++;console.log('PASS '+n)};
function state(jumps=false){let start=T.addDays(T.day(),7),d=new Date(start+'T12:00:00').getDay();let p={...T.blankProfile,goal:'general',minutes:90,weeks:2,start,days:[d,(d+3)%7].sort(),focuses:jumps?['jumping']:[],jumpReady:true};let r=T.buildPlan(p);assert.ok(r.plan,r.errors.join());return{...T.initialState(),profile:p,plan:r.plan,history:[],events:[],proposals:[]}}
function event(date){return{id:'game',name:'Game',date,kind:'Competition',priority:'High',minutes:60,provisional:false}}
test('New competition blocks an existing jump session before start',()=>{let s=state(true),x=s.plan.sessions.find(x=>x.items.some(i=>i.exerciseId==='lib-small-jump-reset'));s.events=[event(T.addDays(x.date,1))];assert.match(T.eligibility(s,x),/too close|protected/)});
test('Cascade rejects new competition proximity without moving any dates',()=>{let s=state(true),x=s.plan.sessions[0];s.events=[event(T.addDays(x.date,5))];let before=JSON.stringify(s);assert.match(T.makeMoveProposal(s,x.id,T.addDays(x.date,3),true).error,/too close|protected/);assert.equal(JSON.stringify(s),before)});
test('Unchanged jump sessions are rechecked when another workout moves',()=>{let s=state(true),jump=s.plan.sessions[0],other=s.plan.sessions[1];other.dependsOn=[];other.recoveryGroup='different';jump.recoveryGroup='jump';assert.ok(T.makeMoveProposal(s,other.id,T.addDays(jump.date,1),false).error)});
test('Restore cannot create a workout collision',()=>{let s=state(),a=s.plan.sessions[0],b=s.plan.sessions[1];a.status='missed';b.date=a.date;let r=T.changeSessionStatus(s,a.id,'scheduled');assert.match(r.error,/already has a workout/);assert.equal(r.state,s)});
test('Restore rejects an existing fixed commitment',()=>{let s=state(),a=s.plan.sessions[0];a.status='missed';s.events=[event(a.date)];assert.match(T.changeSessionStatus(s,a.id,'scheduled').error,/fixed commitment/)});
test('Long machine labels and unbounded timed additions fail before mutation',()=>{let s=state();let a={sessionId:s.plan.sessions[0].id,exercise:T.exFor('triceps'),sets:2,lo:8,hi:12,rest:90,all:false,setup:'x'.repeat(201),allowLonger:true,planId:s.plan.id,version:s.plan.version};assert.match(C.applyAddition(s,a).error,/200 characters/);assert.match(C.applyAddition(s,{...a,exercise:T.exFor('walk'),sets:8,lo:300,hi:300,setup:''}).error,/1,440/)});
test('Non-finite target ranges are rejected',()=>{let s=state();assert.ok(C.previewAddition(s,{sessionId:s.plan.sessions[0].id,exercise:T.exFor('walk'),sets:2,lo:1,hi:NaN,rest:0,all:false,setup:'',allowLonger:true,planId:s.plan.id,version:s.plan.version}).errors.length)});
test('Full archive rejects new block without deleting existing plans',()=>{let s=state();s.saved=Array(100).fill(s.plan);let r=O.acceptSetup(s,s.profile,s.plan,[]);assert.match(r.error,/100/);assert.equal(r.state,s)});
test('Return preview clears old accepted weights and leaves history intact',()=>{let s=state();s.plan.sessions[0].items[0].kg=100;s.plan.sessions[0].items[0].loadContext='Old machine';let p=T.makeProposal(s,'return');assert.equal(p.patch.items[0].kg,null);assert.equal(p.patch.items[0].loadContext,undefined);let before=JSON.stringify(s.history);s.proposals=[p];let r=T.applyProposal(s,p.id);assert.equal(r.error,undefined);assert.equal(JSON.stringify(r.state.history),before)});
test('Prerequisites use the latest timestamp regardless of array ordering',()=>{let s=state(),dep=s.plan.sessions[0],next=s.plan.sessions.find(x=>x.dependsOn?.includes(dep.id));assert.ok(next);let w={id:'ok',sessionId:dep.id,date:dep.date,startedAt:1,finishedAt:3,title:dep.title,sets:dep.items.flatMap(i=>Array.from({length:i.sets},(_,n)=>({exerciseId:i.exerciseId,set:n+1,reps:i.reps,kg:10,done:true}))),partial:false};let failed={...w,id:'partial',finishedAt:2,partial:true};for(let h of [[failed,w],[w,failed]]){s.history=h;assert.equal(T.eligibility(s,next),null)};s.history=[w,{...failed,finishedAt:4}];assert.match(T.eligibility(s,next),/incomplete prerequisite/)});
test('Unknown side values are rejected; alternating data cannot suggest loads',()=>{assert.equal(S.setMetricsSchema.safeParse({side:'leftt'}).success,false);assert.equal(T.comparableSet({metrics:{side:'Alternating'}}),false)});
console.log(count+' deep-audit regression checks passed');
