const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const cache=new Map();
function load(name){if(cache.has(name))return cache.get(name).exports;const m={exports:{}};cache.set(name,m);new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join('lib',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)(s=>s.startsWith('./')?s.endsWith('.json')?JSON.parse(fs.readFileSync(path.join('lib',s),'utf8')):load(s.slice(2)):require(s),m,m.exports);return m.exports;}
const B=load('local-backup'),T=load('training'),D=load('experienced-demo'),S=load('saved-data'),M=load('set-metrics'),P=load('progress');
let checks=0;const test=(name,run)=>{run();checks++;console.log('PASS '+name)};
const clone=x=>JSON.parse(JSON.stringify(x));
test('Backup preserves exact history, unknown and zero loads, Unicode notes and optional measurements',()=>{
 const incoming=D.experiencedDemo();incoming.history[0].sets[0].kg=null;incoming.history[0].sets[1].kg=0;
 incoming.history[0].sets[0].metrics={distanceM:0,durationSeconds:60,heightCm:45,heartRate:132,cadence:90,powerWatts:120,speedKph:8.5,inclinePercent:-3,level:2,assistanceKg:10,tempo:'3–1–1',side:'Left',notes:'Test notes · café 🏋️'};
 const raw=B.serializeBackup(incoming),preview=B.previewBackup(raw),current=T.initialState(),restored=B.restoreBackup(current,preview.state,B.serializeBackup(current));
 assert.deepEqual(restored.history,incoming.history);assert.equal(restored.history[0].sets[0].kg,null);assert.equal(restored.history[0].sets[1].kg,0);
 assert.equal(preview.workouts,incoming.history.length);assert.equal(restored.restTimer,null);assert.equal(restored.restAlerts,false);assert.equal(restored.simulatedOffline,false);assert.deepEqual(S.readSavedState(JSON.stringify(restored)),restored);
 assert.ok(M.metricSummary(restored.history[0].sets[0].metrics).includes('Incline (%): -3'));assert.ok(M.metricSummary({distanceM:0}).includes(': 0'));
});
test('Only reviewed known fields can leave a backup',()=>{const state=T.initialState();state.unrecognized='SYNTHETIC-DO-NOT-EXPORT';state.profile.secret='SYNTHETIC-DO-NOT-EXPORT';assert.ok(!B.serializeBackup(state).includes('SYNTHETIC-DO-NOT-EXPORT'));});
test('Restore rejects a stale preview and leaves current records unchanged',()=>{const current=T.initialState(),expected=B.serializeBackup(current),edited=T.changed(current,'Later test edit'),before=JSON.stringify(edited);assert.throws(()=>B.restoreBackup(edited,D.experiencedDemo(),expected),/changed after this preview/);assert.equal(JSON.stringify(edited),before);});
test('Restore protects an in-progress workout',()=>{const current=T.initialState(),session=current.plan.sessions[0];current.active={id:'test-active',sessionId:session.id,title:session.title,date:session.date,startedAt:Date.now(),targets:session.items,sets:session.items.flatMap(item=>Array.from({length:item.sets},(_,i)=>({exerciseId:item.exerciseId,set:i+1,reps:0,kg:null,done:false}))),loadContext:{},rir:{}};const expected=B.serializeBackup(current);assert.throws(()=>B.restoreBackup(current,D.experiencedDemo(),expected),/Finish or discard/);assert.equal(current.active.id,'test-active');});
test('Restored proposals need review; concern holds and logged actuals stay intact',()=>{const incoming=T.initialState(),proposal=T.makeProposal(incoming,'sets');assert.ok(proposal);incoming.proposals=[{...proposal,status:'queued'}];incoming.hold=true;const current=T.initialState(),restored=B.restoreBackup(current,incoming,B.serializeBackup(current));assert.equal(restored.proposals[0].status,'stale');assert.equal(restored.hold,true);assert.deepEqual(restored.plan,clone(incoming.plan));});
test('Malformed, prototype-polluting, oversized and invalid-record backups fail before replacement',()=>{for(const raw of ['{','null','[]','{"__proto__":{"x":1}}',' '.repeat(5000001)])assert.throws(()=>B.previewBackup(raw));const invalid=clone(T.initialState());invalid.profile.age=1e9;assert.throws(()=>B.serializeBackup(invalid));assert.equal(({}).x,undefined);});
test('Assisted or one-sided sets cannot create an adult strength estimate',()=>{const base={id:'test',sessionId:'test',title:'Test',date:T.day(),startedAt:1,finishedAt:2,partial:false,symptom:'no',rir:{bench:1},sets:[{exerciseId:'bench',set:1,reps:6,kg:50,done:true}]};assert.ok(P.estimatedMax(base,'bench')>50);assert.equal(P.estimatedMax({...base,sets:[{...base.sets[0],metrics:{assistanceKg:10}}]},'bench'),null);assert.equal(P.estimatedMax({...base,sets:[{...base.sets[0],metrics:{side:'Left'}}]},'bench'),null);});
console.log(`${checks} backup and measurement checks passed.`);
