const OriginalDate=Date;global.Date=class extends OriginalDate{constructor(...a){super(...(a.length?a:['2026-10-07T17:00:00Z']))}static now(){return new OriginalDate('2026-10-07T17:00:00Z').getTime()}};
const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');const dir='.sites-runtime/catalog-checks';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/package.json','{"type":"commonjs"}');for(const f of ['training','training-focus','program-catalog','customize','progress','experienced-demo'])fs.writeFileSync(dir+'/'+f+'.js',ts.transpileModule(fs.readFileSync('lib/'+f+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText);for(const f of ['recipes','exercise-library'])fs.copyFileSync('lib/'+f+'.json',dir+'/'+f+'.json');
const E=require('../'+dir+'/training.js'),C=require('../'+dir+'/customize.js'),P=require('../'+dir+'/progress.js'),D=require('../'+dir+'/experienced-demo.js'),catalog=require('../'+dir+'/program-catalog.js').programCatalog;
let n=0;function test(name,fn){try{fn();console.log('PASS',name);n++}catch(e){console.error('FAIL',name,e.message);process.exitCode=1}}
function state(def){const p={...E.blankProfile,goal:def.goal,programId:def.id,days:[0,1,2,3,4,5,6],minutes:120,weeks:8,runBase:true,runDays:4,runMinutes:100,experience:'Experienced',establishedTraining:true,start:E.day()};const r=E.buildPlan(p);assert.equal(r.errors.length,0,r.errors.join());return{...E.initialState(),profile:p,plan:r.plan}}
test('All catalog program types start at slot A and preserve safe groups during cascade',()=>{for(const def of catalog){const s=state(def);assert.equal(s.plan.sessions[0].title,def.slots[0].title);assert.equal(s.plan.sessions.length,8*def.days);assert.ok(E.makeMoveProposal(s,s.plan.sessions[0].id,E.addDays(s.plan.sessions[0].date,1),true).proposal,def.id)}});
test('Powerlifting includes SBD, contains no endurance, and rejects missing gym',()=>{for(const def of catalog.filter(x=>x.goal==='powerlifting')){const s=state(def),ids=s.plan.sessions.flatMap(x=>x.items.map(i=>i.exerciseId));for(const id of ['bar-squat','bench','deadlift'])assert.ok(ids.includes(id));assert.ok(!ids.includes('run'));assert.ok(E.buildPlan({...s.profile,equipment:'Dumbbells'}).errors.length)}});
test('Catalog IDs unique; equipment subdivisions and core present',()=>{assert.equal(new Set(E.exercises.map(x=>x.id)).size,E.exercises.length);for(const eq of ['Barbell','Dumbbell','Kettlebell','Cable','Plate-loaded machine','Selectorized machine'])assert.ok(E.exercises.filter(x=>x.equipment===eq).length>=10);assert.ok(E.exercises.filter(x=>x.pattern==='Core').length>30)});
test('Customization adds recurring sets without changing history; duplicate and stale writes fail',()=>{const s=state(catalog[0]),ex=E.exFor('core-kneeling-cable-crunch');assert.notEqual(ex.name,'Archived exercise');const a={sessionId:s.plan.sessions[0].id,exercise:ex,sets:2,lo:8,hi:12,rest:90,all:true,setup:'Cable A',allowLonger:false,planId:s.plan.id,version:s.plan.version};const preview=C.previewAddition(s,a);assert.equal(preview.errors.length,0,preview.errors.join());assert.equal(preview.changes.length,8);const r=C.applyAddition(s,a);assert.ok(!r.error,r.error);assert.deepEqual(r.state.history,s.history);assert.ok(r.state.plan.sessions[0].items.some(x=>x.exerciseId===ex.id));assert.ok(C.applyAddition(r.state,a).error);assert.ok(C.applyAddition(r.state,{...a,version:r.state.plan.version}).error)});
test('Added loaded exercise uses its own configured range history for progression',()=>{let s=state(catalog[0]);const ex=E.exercises.find(x=>x.id==='lib-plate-chest-press');const i={exerciseId:ex.id,sets:2,reps:8,repMin:8,repMax:12,rest:90,kg:null};s.loadContext={[ex.id]:'Machine A'};s.incrementKg={[ex.id]:2.5};s.history=[0,3].map(d=>({id:'r'+d,sessionId:'old'+d,title:'test',date:E.addDays(E.day(),-d),startedAt:1,finishedAt:2,targets:[i],sets:[1,2].map(n=>({exerciseId:ex.id,set:n,done:true,kg:50,reps:12})),rir:{[ex.id]:2},symptom:'no',effort:'right',loadContext:{[ex.id]:'Machine A'}}));assert.equal(E.loadSuggestion(s,i).nextKg,52.5);s.loadContext[ex.id]='Machine B';assert.equal(E.loadSuggestion(s,i).kg,null)});
test('Heavy bench cannot become practice starting load',()=>{let s=state(catalog[0]);const heavy=s.plan.sessions[0].items.find(i=>i.exerciseId==='bench'),practice=s.plan.sessions[1].items.find(i=>i.exerciseId==='bench');s.history=[{id:'h',sessionId:'x',title:'heavy',date:E.day(),startedAt:1,finishedAt:2,targets:[heavy],sets:[1,2,3].map(n=>({exerciseId:'bench',set:n,done:true,reps:6,kg:100})),symptom:'no',rir:{bench:2}}];assert.equal(E.loadSuggestion(s,practice).kg,null)});
test('Volume counts per-hand/per-side multipliers, partial actuals and excludes unknowns',()=>{const s=E.initialState();const w={sets:[{exerciseId:'row',done:true,reps:10,kg:20},{exerciseId:'bench',done:false,reps:10,kg:100},{exerciseId:'plank',done:true,reps:30,kg:null}]};assert.deepEqual(P.volume(s,w),{kg:400,count:1,excluded:1})});
test('Generated sample gives 34 logs, one partial and nonempty exercise/volume/index charts',()=>{const s=D.experiencedDemo();assert.equal(s.history.length,34);assert.equal(s.history.filter(w=>w.partial).length,1);assert.ok(P.exerciseSeries(s,'bench').length>20);assert.ok(P.strengthIndex(s).current>100);assert.ok(s.history.every(w=>w.demo))});
test('Strength index expires each component against today and youth has none',()=>{const s=D.experiencedDemo();s.history=s.history.map(w=>({...w,date:E.addDays(w.date,-24)}));assert.equal(P.strengthIndex(s).current,null);s.profile.age=15;assert.equal(P.strengthIndex(s).current,null)});
console.log(n+' catalog and progress checks passed');
