const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict');
const dir='.sites-runtime/focus-check';fs.mkdirSync(dir,{recursive:true});
for(const file of ['record-identity','program-catalog','program-evidence','training','training-focus'])fs.writeFileSync(dir+'/'+file+'.js',ts.transpileModule(fs.readFileSync('lib/'+file+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText);
fs.writeFileSync(dir+'/package.json','{"type":"commonjs"}');for(const file of ['recipes','exercise-library'])fs.copyFileSync('lib/'+file+'.json',dir+'/'+file+'.json');
const T=require('../'+dir+'/training.js'),F=require('../'+dir+'/training-focus.js');let checks=0;
const profile={...T.blankProfile,name:'Alex',start:'2026-10-12',goal:'general',minutes:90,days:[1,4],weeks:2,experience:'Some experience',focuses:[],jumpReady:true};
function test(name,fn){fn();checks++;console.log('PASS '+name)}
function base(p={}){const result=T.buildPlan({...profile,...p});assert.ok(result.plan,result.errors.join(' '));return result.plan}
function apply(plan,focuses,patch={},events=[]){return F.applyTrainingFocus({...plan,profile:{...plan.profile,focuses,...patch}},events)}
test('All four compatible add-ons preserve dates and fit the hard time window',()=>{const original=base(),result=apply(original,['core','jumping','supersets','activity']);assert.ok(result.plan,result.errors.join(' '));assert.deepEqual(result.plan.sessions.map(s=>s.date),original.sessions.map(s=>s.date));assert.ok(result.plan.sessions.every(s=>s.minutes<=90));assert.ok(result.plan.sessions.some(s=>s.items.some(i=>i.exerciseId==='walk')));assert.equal(original.sessions.some(s=>s.items.some(i=>i.note?.includes('[Focus]'))),false)});
test('The central buildPlan path applies focus choices',()=>{const result=T.buildPlan({...profile,focuses:['jumping','activity']});assert.ok(result.plan,result.errors.join(' '));assert.ok(result.plan.sessions.some(s=>s.items.some(i=>i.exerciseId==='lib-small-jump-reset')));assert.ok(result.plan.sessions.some(s=>s.items.some(i=>i.exerciseId==='walk')))});
test('No spare time rejects add-ons without trimming primary work',()=>{const original=base();const max=Math.max(...original.sessions.map(s=>s.minutes));const result=apply(original,['activity'],{minutes:max});assert.equal(result.plan,null);assert.match(result.errors.join(' '),/ten spare minutes/)});
test('Jump dose is small, first after warm-up, and capped once per week',()=>{const result=apply(base(),['jumping']);assert.ok(result.plan);for(const week of [1,2]){const jump=result.plan.sessions.filter(s=>s.week===week&&s.items[0]?.exerciseId==='lib-small-jump-reset');assert.equal(jump.length,1);assert.equal(jump[0].items[0].sets,2);assert.equal(jump[0].items[0].reps,3);assert.equal(jump[0].items[0].kg,null);assert.equal(jump[0].items[0].rest,120)}});
test('Nearby practices can make jump selection unavailable; no date is moved',()=>{const plan=base();const events=plan.sessions.map((s,i)=>({id:String(i),name:'Practice',date:T.addDays(s.date,1),kind:'Team practice',priority:'Normal',minutes:60,provisional:false}));const result=apply(plan,['jumping'],{},events);assert.equal(result.plan,null);assert.match(result.errors.join(' '),/48 hours/)});
test('New jump users need supervision even with self-reported readiness',()=>{const r=apply(base(),['jumping'],{experience:'First time',supervision:false});assert.equal(r.plan,null);assert.match(r.errors.join(' '),/qualified supervision/)});
test('Youth jump work has one set and needs supervision',()=>{const youth=base({age:16,supervision:true});const result=apply(youth,['jumping']);assert.ok(result.plan,result.errors.join(' '));assert.ok(result.plan.sessions.flatMap(s=>s.items).filter(i=>i.exerciseId==='lib-small-jump-reset').every(i=>i.sets===1&&i.reps===3));assert.equal(apply(youth,['jumping'],{supervision:false}).plan,null)});
test('Youth weight-management and superset selections cannot add adult doses',()=>{const youth=base({age:16,supervision:true});for(const focus of ['activity','supersets'])assert.equal(apply(youth,[focus]).plan,null)});
test('Coach and manual tracking remain free of automatic prescriptions',()=>{for(const mode of ['coach','manual']){const original=base({mode});const result=apply(original,['jumping','activity','core','supersets'],{jumpReady:false});assert.ok(result.plan);assert.deepEqual(result.plan.sessions,original.sessions);assert.ok(result.plan.notes.some(n=>n.includes('no work, rest or dates were added')))}});
test('Supersets preserve primary lift dose and combine only assistance rest',()=>{const original=base();const result=apply(original,['supersets']);assert.ok(result.plan,result.errors.join(' '));for(const s of result.plan.sessions){const before=original.sessions.find(x=>x.id===s.id);for(const i of before.items.filter(x=>!['calf','deadbug'].includes(x.exerciseId)))assert.deepEqual(s.items.find(x=>x.exerciseId===i.exerciseId),i);const a=s.items.find(i=>i.note?.includes('A1.')),b=s.items.find(i=>i.note?.includes('A2.'));assert.ok(a&&b);assert.equal(a.rest,0);assert.equal(b.rest,before.items.find(i=>i.exerciseId===a.exerciseId).rest+before.items.find(i=>i.exerciseId===b.exerciseId).rest);assert.equal(s.minutes,before.minutes)}});
test('Powerlifting main lifts are never forced into a superset',()=>{const plan=base({goal:'powerlifting',programId:'PL3',days:[1,3,5],minutes:120});const r=apply(plan,['supersets']);assert.equal(r.plan,null);assert.match(r.errors.join(' '),/no compatible assistance pair/);assert.equal(apply(plan,['jumping']).plan,null)});
test('Activity focus does not silently increase a run-only program',()=>{const plan=base({goal:'running',days:[1,3,5],minutes:60});const r=apply(plan,['activity']);assert.ok(r.plan);assert.deepEqual(r.plan.sessions,plan.sessions);assert.ok(r.plan.notes.some(n=>n.includes('existing easy running/walking')))});
test('Applied focus plans are idempotent',()=>{const r=apply(base(),['core','jumping','activity']);assert.ok(r.plan);assert.deepEqual(F.applyTrainingFocus(r.plan).plan,r.plan)});
console.log(checks+' focus checks passed');
