const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const cache=new Map();
function load(name){if(cache.has(name))return cache.get(name).exports;const module={exports:{}};cache.set(name,module);const code=ts.transpileModule(fs.readFileSync(path.join('lib',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText;new Function('require','module','exports',code)(s=>s.startsWith('./')?s.endsWith('.json')?JSON.parse(fs.readFileSync(path.join('lib',s),'utf8')):load(s.slice(2)):require(s),module,module.exports);return module.exports;}
const T=load('training'),P=load('progress'),S=load('saved-data');
const guides=JSON.parse(fs.readFileSync('public/exercise-guides.json','utf8')),media=JSON.parse(fs.readFileSync('public/exercise-content.json','utf8'));
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('Every shipped catalog entry has a complete movement guide and logging convention',()=>{assert.equal(T.exercises.length,989);assert.equal(Object.keys(guides).length,989);for(const e of T.exercises){const g=guides[e.id];assert.ok(g,e.id);for(const k of ['variant','summary','equipment','setup','execution','finish','breathing','commonErrors','easierOption','safety','loadConvention','sourceURLs','sourceNote'])assert.ok(g[k]?.length,e.id+' '+k);assert.ok(e.loadConvention,e.id);assert.equal(new Set(g.sourceURLs).size,g.sourceURLs.length,e.id+' duplicate source');for(const u of g.sourceURLs){const url=new URL(u);assert.equal(url.protocol,'https:');assert.ok(!url.username&&!url.password);}if(e.id.startsWith('ref-')){assert.equal(e.instructionStatus,'source-described');assert.equal(e.cues.length,3);assert.equal(g.loadConvention,e.loadConvention);assert.equal(e.loadTracked,e.loadMultiplier>0);if(e.progressionEnabled)assert.ok(e.loadTracked&&e.metric==='reps');}}});
test('Unverified photo candidates are withheld; guide and source coverage stays complete',()=>{assert.equal(load('exercise-content').exercisePhotoRightsCleared,false);assert.ok(Object.keys(media).length>=T.exercises.filter(e=>e.id.startsWith('ref-')).length);let count=0;for(const [id,m] of Object.entries(media))for(const image of m.images||[]){assert.match(image,/^\/exercise-photos\/[a-zA-Z0-9_/-]+\.jpg$/);assert.equal(m.sourceRecordId,id.slice(4));assert.equal(fs.existsSync('public'+image),false,'Uncleared photo was shipped: '+image);count++;}assert.ok(count>1700);console.log('  '+count+' candidate photo references withheld');});
test('Multiword and common abbreviation searches work regardless of word order',()=>{const e=T.exFor('squat');assert.ok(T.matchesExercise(e,'squat db'));assert.ok(T.matchesExercise(e,'dumbell goblet'));assert.ok(!T.matchesExercise(e,'cable'));assert.ok(T.matchesExercise(T.exFor('plank'),'abs'));});
test('Optional measurements survive a validated save and invalid values are rejected',()=>{const s=T.initialState(),ss=s.plan.sessions[0];s.active={id:'metric-test',sessionId:ss.id,title:ss.title,date:ss.date,startedAt:1,targets:[{exerciseId:'walk',sets:1,reps:10,rest:0,kg:null}],sets:[{exerciseId:'walk',set:1,reps:10,kg:null,done:true,metrics:{distanceM:750,durationSeconds:600,heightCm:20,heartRate:125,cadence:80,powerWatts:150,speedKph:4.5,inclinePercent:-2,level:4,assistanceKg:5,tempo:'3-1-1',side:'Both',notes:'Track one'}}]};const restored=S.readSavedState(JSON.stringify(s));assert.deepEqual(restored.active.sets[0].metrics,s.active.sets[0].metrics);for(const invalid of [{distanceM:-1},{durationSeconds:Infinity},{heartRate:999},{notes:'x'.repeat(6001)}])assert.equal(S.setMetricsSchema.safeParse(invalid).success,false);});
test('One-sided and assisted records do not drive load or maximum suggestions',()=>{const s=T.initialState(),item={exerciseId:'row',sets:1,reps:8,repMin:8,repMax:12,rest:90,kg:null};s.history=[0,3].map(d=>({id:'h'+d,sessionId:'old'+d,title:'Row',date:T.addDays(T.day(),-d),startedAt:1,finishedAt:2,targets:[item],sets:[{exerciseId:'row',set:1,reps:12,kg:20,done:true,metrics:{side:'Left'}}],rir:{row:2},symptom:'no',effort:'right'}));assert.equal(T.loadSuggestion(s,item).nextKg,undefined);assert.equal(P.estimatedMax({...s.history[0],sets:[{...s.history[0].sets[0],reps:8}]},'row'),null);assert.deepEqual(P.volume(s,s.history[0]),{kg:240,count:1,excluded:0});s.history[0].sets[0].metrics={assistanceKg:5};assert.deepEqual(P.volume(s,s.history[0]),{kg:0,count:0,excluded:1});});
test('Unsupported timed and skill movements do not produce estimated 1RM points',()=>{const s=T.initialState(),e=T.exercises.find(e=>e.loadTracked&&!e.progressionEnabled);assert.ok(e);s.history=[{id:'h',sessionId:'old',title:'Practice',date:T.day(),startedAt:1,finishedAt:2,sets:[{exerciseId:e.id,set:1,reps:5,kg:20,done:true}],rir:{[e.id]:1},symptom:'no'}];assert.equal(P.exerciseSeries(s,e.id)[0].estimated,null);});
console.log(passed+' full-library and measurement checks passed');
