import {exFor, type Plan, type Session} from './training';
import {programReferences} from './program-catalog';
export function sessionGuide(plan:Plan,session:Session){
 const youth=plan.profile.age<18,run=!!session.runSteps,manual=plan.profile.mode!=='app';
 const source=programReferences.find(r=>r.id===plan.profile.programId);
 if(source)return {warmup:['Follow the warm-up and technique guidance in the linked source. Practice sets are separate from these work sets.','The session estimate includes preparation and app rest defaults. Allow more time when needed.'],effort:session.items.some(i=>i.note?.includes('[AMRAP]'))?'The + applies only to the final indicated set. Follow the source’s effort and form limits; log actual extra reps.': 'Follow the source’s effort rules and choose manageable starting loads. Loading and resets remain manual.',finish:'Save the work you completed. Review the author’s progression before editing future targets.'};
 if(manual)return {warmup:['Use the warm-up and targets from your coach or your own plan.'],effort:'Your coach or plan sets the effort.',finish:'Save only the work you did. Keep any coach instructions with this session.'};
 if(run)return {warmup:session.runSteps!.map(s=>`${s.label}: ${s.seconds>=60?Math.round(s.seconds/6)/10+' min':s.seconds+' sec'}`),effort:'Keep an easy pace that lets you talk in full sentences. Walk when needed. Do not add speed to make up a missed run.',finish:'Include the closing walk when you log your time. Finish this workout before moving to the next stage.'};
 if(session.timeProfile==='brief')return {warmup:['Spend about 5 minutes preparing: easy movement, then a few light practice reps of each strength exercise today. This focused warm-up is included in the estimate.','Read the setup before starting. If an exercise is unfamiliar or needs more practice, allow more time or finish fewer work sets; do not rush the listed rest.',...(session.items.some(i=>i.exerciseId==='lib-small-jump-reset')?['Do only the listed jumps and reset fully between reps. Do not add extra practice jumps.']:[]),...(session.items.some(i=>exFor(i.exerciseId).equipment==='Barbell')?['For a familiar barbell lift, allow the extra ramp-up time in the estimate for light practice sets. Heavy or unfamiliar work may need longer; do not rush to fit the clock.']:[]),...(youth?['Your qualified supervisor chooses the variation, starting load and any extra practice.']:[])],effort:youth?'Use controlled reps with your qualified supervisor. No sets to failure or maximum tests.':'Keep 2–3 controlled reps left (RIR). These brief sessions provide less work; longer available time does not require extra sets.',finish:'Use the final minute to settle and record actual work. Practice sets are not work sets. No catch-up work after a missed or partial session.'};
 const firstItem=session.items.find(i=>i.exerciseId!=='lib-small-jump-reset'&&exFor(i.exerciseId).metric==='reps');const first=firstItem&&exFor(firstItem.exerciseId).name;
 return {warmup:[
 'Start with 5 minutes of easy walking, cycling or similar movement.',
 'Move the joints used today through a comfortable range for 2–3 minutes. Read the setup for each unfamiliar exercise.',
 `${first?'Before '+first.toLowerCase()+' and each new strength movement':'Before each new strength movement'}, try 5–8 controlled reps with little or no load. These are practice reps, not work sets.`,
 ...(session.items.some(i=>i.exerciseId==='lib-small-jump-reset')?['For jump practice, do only the listed jumps and reset fully between reps. Do not add extra practice jumps.']:[]),
 youth?'Have your qualified supervisor choose the version and starting load. Ask for more practice or rest when needed.':'For a heavier barbell lift, add 1–3 short warm-up sets with small load steps. Keep them easy; use a lighter training bar if the standard bar is too heavy.'
 ],effort:youth?'Keep every rep controlled. Your supervisor chooses the effort; no max tests or sets to failure.':'Aim to finish work sets with about 2–3 good reps left (RIR). While learning, use less weight. The listed rest starts after both sides of a per-side exercise.',finish:'Take 2–3 easy minutes to finish. Save actual work sets, RIR and feedback. Warm-up work is not a strength record. More practice or rest may make the session longer.'};
}
